'use strict';
class BattleAnimator {
 constructor(container){this.videos=[0,1].map(()=>{const v=document.createElement('video');v.muted=true;v.defaultMuted=true;v.autoplay=true;v.playsInline=true;v.loop=true;v.preload='auto';v.className='fish-video';container.append(v);return v;});this.front=0;this.current='';this.pending='';this.generation=0;this.lastChange=0;this.priority=0;this.timer=null;this.loads=0;this.frames=0;this.errors=[];this.failed=new Set();this.cycle=null;for(const v of this.videos){v.addEventListener('timeupdate',()=>{if(v!==this.videos[this.front]||!this.cycle)return;const [start,tail]=this.cycle;if(v.duration&&v.currentTime>v.duration-tail)v.currentTime=Math.min(start,v.duration*.25);});}}
 set(name,priority=0){const now=performance.now();if(!name||this.failed.has(name)||name===this.current||name===this.pending)return;if(priority<90&&priority<=this.priority&&now-this.lastChange<650)return;
  const gen=++this.generation;this.pending=name;clearTimeout(this.timer);const v=this.videos[1-this.front];v.onloadeddata=null;v.onerror=null;
  let committed=false;const commit=()=>{if(gen!==this.generation||committed)return;committed=true;clearTimeout(this.timer);const old=this.videos[this.front];old.classList.remove('front');old.pause();v.classList.add('front');this.front=1-this.front;this.current=name;this.pending='';this.lastChange=performance.now();this.priority=priority;this.cycle=name==='原地左转奔跑'?[1.75,4.8]:name==='螃蟹走路'?[2,2]:null;if(this.cycle&&v.duration>4)v.currentTime=Math.min(this.cycle[0],v.duration*.25);v.play().catch(err=>{if(gen!==this.generation||err.name==='AbortError')return;this.errors.push(err.message);window.battleBridge.report(err.message);});this.loads++;if(v.requestVideoFrameCallback){const count=()=>{if(gen!==this.generation)return;this.frames++;v.requestVideoFrameCallback(count);};v.requestVideoFrameCallback(count);}};
  const fail=()=>{if(gen!==this.generation)return;clearTimeout(this.timer);this.pending='';this.failed.add(name);const error='动画加载失败：'+name;this.errors.push(error);if(this.errors.length>20)this.errors.shift();window.battleBridge.report(error);if(!this.current&&name!=='待机呼吸休闲')this.set('待机呼吸休闲',100);};v.onloadeddata=commit;v.onerror=fail;v.src=new URL('../../../../assets/webm/'+encodeURIComponent(name)+'.webm',location.href).href;v.load();this.timer=setTimeout(fail,10000);if(v.readyState>=2)commit();
 }
 dispose(){++this.generation;clearTimeout(this.timer);for(const v of this.videos){v.pause();v.onloadeddata=null;v.onerror=null;v.removeAttribute('src');v.load();v.remove();}}
}
window.BattleAnimator=BattleAnimator;
