'use strict';
const $=id=>document.getElementById(id);let count=6,busy=false,mode='setup',paused=false,current=null,draft=null,catalog=[],bookTab='catalog',fishIndex=0,readonly=false;
for(let n=2;n<=10;n++){const b=document.createElement('button');b.className='count'+(n===count?' selected':'');b.textContent=n+' 条';b.dataset.count=n;b.onclick=()=>{count=n;for(const node of $('counts').children)node.classList.toggle('selected',Number(node.dataset.count)===n);};$('counts').append(b);}
async function action(name,payload={}){if(busy)return;busy=true;$('error').textContent='';for(const b of document.querySelectorAll('button'))b.disabled=true;try{const result=await battleBridge.action(name,payload);if(result?.ok===false)$('error').textContent=result.error||'操作未完成';return result;}catch(err){$('error').textContent=err.message;}finally{busy=false;for(const b of document.querySelectorAll('button'))b.disabled=false;if(mode==='skills')lockReadonly();}}
$('start').onclick=()=>action('start',{count,seed:$('seed').value===''?null:Number($('seed').value)});$('cancel').onclick=()=>action('cancel');$('close').onclick=()=>action(mode==='result'?'stop':'cancel');$('end').onclick=$('stop').onclick=()=>action('stop');$('again').onclick=()=>action('again',{count:current?.result?.count||count});$('pause').onclick=()=>action('pause');
$('close').onclick=()=>action(mode==='skills'?'back-skills':mode==='result'?'stop':'cancel');
for(const [id,tab]of [['book','catalog'],['configure','custom'],['events-entry','events'],['live-book','catalog']])$(id).onclick=()=>action('skills',{tab,count:mode==='setup'?count:null});
$('book-back').onclick=()=>action('back-skills');$('save-setup').onclick=()=>action('save-setup',{setup:draft});
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{bookTab=b.dataset.tab;$('skill-filter').value='all';$('skill-search').value='';$('book-scroll').scrollTop=0;renderBook();};
for(const b of document.querySelectorAll('[data-mode]'))b.onclick=()=>{draft.mode=b.dataset.mode;renderBook();};
function button(text,click,className=''){const b=document.createElement('button');b.textContent=text;b.onclick=click;b.className=className;return b;}
function summary(setup){const names=setup.events.map(id=>catalog.find(s=>s.id===id)?.name).filter(Boolean);return (setup.mode==='custom'?'自选技能':'每局随机技能')+' · '+(names.length?names.join('、')+'（'+current.eventRates?.[setup.eventRate]?.label+'）':'场外事件全部关闭');}
function toggleSkill(s){if(readonly)return;const row=draft.fish[fishIndex],key=s.slot==='ultimate'?'ultimates':'skills',limit=key==='ultimates'?2:current.maxSkills;const at=row[key].indexOf(s.id);if(at>=0)row[key].splice(at,1);else if(row[key].length>=limit){$('error').textContent=`这条鱼最多选择 ${limit} 个${key==='skills'?'普通技能':'大招'}`;return;}else row[key].push(s.id);draft.mode='custom';$('error').textContent='';renderBook();}
function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
$('random-fish').onclick=()=>{const ids=slot=>shuffle(catalog.filter(s=>s.slot===slot)).map(s=>s.id);draft.fish[fishIndex]={skills:[...ids('attack').slice(0,2),ids('utility')[0],ids('sustain')[0],ids('special')[0]],ultimates:['29','30']};draft.mode='custom';renderBook();};
$('copy-fish').onclick=()=>{draft.fish=draft.fish.map(()=>structuredClone(draft.fish[fishIndex]));draft.mode='custom';renderBook();};
$('clear-fish').onclick=()=>{draft.fish[fishIndex]={skills:[],ultimates:[]};draft.mode='custom';renderBook();};
$('food-count').onchange=()=>{draft.foodCount=Number($('food-count').value);renderBook();};
$('can-count').onchange=()=>{draft.canCount=Number($('can-count').value);};
$('events-all').onclick=()=>{draft.events=catalog.filter(s=>s.slot==='event').map(s=>s.id);renderBook();};$('events-none').onclick=()=>{draft.events=[];renderBook();};$('skill-search').oninput=$('skill-filter').onchange=()=>renderList();
function lockReadonly(){for(const b of document.querySelectorAll('#custom-options button,#event-options button,.choose-skill'))b.disabled=readonly;$('save-setup').hidden=readonly;}
function renderBook(){
 for(const b of document.querySelectorAll('[data-tab]'))b.classList.toggle('selected',b.dataset.tab===bookTab);
 $('custom-options').hidden=bookTab!=='custom';$('event-options').hidden=bookTab!=='events';$('catalog-tools').hidden=bookTab==='events';$('readonly-note').hidden=!readonly;$('draft-summary').textContent=readonly?'观战图鉴':'保存后下次打开仍会保留';
 if(bookTab==='custom'){for(const b of document.querySelectorAll('[data-mode]'))b.classList.toggle('selected',draft.mode===b.dataset.mode);fishIndex=Math.min(fishIndex,draft.count-1);$('fish-tabs').replaceChildren(...Array.from({length:draft.count},(_,i)=>button('鱼'+(i+1),()=>{fishIndex=i;renderBook();},i===fishIndex?'selected':'')));const r=draft.fish[fishIndex];$('selected-skills').replaceChildren(...[...r.skills,...r.ultimates].map(id=>{const s=catalog.find(s=>s.id===id);return button(s.name+(s.slot==='ultimate'?' ★':'')+' ×',()=>toggleSkill(s),'skill-pill');}));if(!r.skills.length)$('selected-skills').textContent='还没选普通技能';const offense=r.skills.some(id=>catalog.find(s=>s.id===id).damage>0);$('loadout-warning').textContent=draft.mode==='random'?'当前采用随机模式；下面的自选组合会保留，切换“我来配技能”后生效。':!r.skills.length?'至少选 1 个普通技能才能保存。':!offense?'当前只有功能或恢复技能，可能会打得很慢。':r.skills.some(id=>catalog.find(s=>s.id===id).requiredEnemies>=draft.count)?'有技能需要更多对手；本局人数不足时，该技能不会自动触发。':`鱼${fishIndex+1}：${r.skills.length} 个普通技能 · ${r.ultimates.length} 个大招`;
 }
 if(bookTab==='events'){$('food-count').replaceChildren(...Array.from({length:current.maxFood},(_,i)=>{const o=document.createElement('option');o.value=i+1;o.textContent=(i+1)+' 份'+(i===2?'（推荐）':'');o.selected=draft.foodCount===i+1;return o;}));$('food-count').disabled=readonly;$('can-count').replaceChildren(...Array.from({length:current.maxCans},(_,i)=>{const o=document.createElement('option');o.value=i+1;o.textContent=(i+1)+' 个'+(i===2?'（推荐）':'');o.selected=draft.canCount===i+1;return o;}));$('can-count').disabled=readonly;$('food-count').title='当前每份回复 '+Math.round(Math.min(current.foodHeal,current.foodWaveBudget/draft.foodCount)*10)/10+' HP；每轮总回复最多 '+current.foodWaveBudget+' HP';$('event-rates').replaceChildren(...Object.entries(current.eventRates).map(([id,spec])=>button(spec.label,()=>{draft.eventRate=id;renderBook();},draft.eventRate===id?'selected':'')));const interval=current.eventRates[draft.eventRate].interval;$('event-summary').textContent=draft.events.length?`每隔约 ${interval[0]}～${interval[1]} 秒抽取一次；当前小鱼干每份 ${Math.round(Math.min(current.foodHeal,current.foodWaveBudget/draft.foodCount)*10)/10} HP。一局不保证每种都出现。罐头每个落点独立预警，错开少许时间落下。`:'全部关闭：本局不会触发随机场外事件。';}
 renderList();lockReadonly();
}
function renderList(){const search=$('skill-search').value.trim().toLowerCase(),filter=$('skill-filter').value;const list=catalog.filter(s=>bookTab==='events'?s.slot==='event':(bookTab!=='custom'||s.slot!=='event')&&(filter==='all'||s.slot===filter)&&(!search||(s.name+s.detail+s.condition).toLowerCase().includes(search)));$('skill-list').replaceChildren(...list.map(s=>{
 const card=document.createElement('article');card.className='skill-card';card.dataset.skill=s.id;const head=document.createElement('div');head.className='skill-head';const img=document.createElement('img');img.src='../../../../assets/battle/'+s.icon;img.alt='';const title=document.createElement('div'),strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=s.name;small.textContent=s.group+' · '+s.id;title.append(strong,small);head.append(img,title);
 if(bookTab==='custom'){const r=draft.fish[fishIndex],chosen=[...r.skills,...r.ultimates].includes(s.id);head.append(button(chosen?'已选择 ✓':'选择',()=>toggleSkill(s),'choose-skill'+(chosen?' chosen':'')));}
 if(bookTab==='events'){const on=draft.events.includes(s.id);head.append(button(on?'开启 ✓':'已关闭',()=>{draft.events=on?draft.events.filter(id=>id!==s.id):[...draft.events,s.id];renderBook();},'choose-skill'+(on?' chosen':'')));}
 const p=document.createElement('p');p.textContent=s.detail;const d=document.createElement('details'),sum=document.createElement('summary'),stats=document.createElement('p');sum.textContent='数值与使用条件';stats.textContent=(s.slot==='event'?'使用所选场外频率。':`基础伤害 ${s.damage} · 冷却 ${s.cooldown}s · 前摇 ${s.cast}s · 生效 ${s.active}s · 后摇 ${s.recovery}s。`)+'\n自动使用：'+s.condition;stats.style.whiteSpace='pre-wrap';d.append(sum,stats);card.append(head,p,d);return card;}));if(!list.length)$('skill-list').textContent='没有找到这个技能，试试其他名字。';lockReadonly();}
function row(r){const div=document.createElement('div');div.className='row'+(r.rank===1?' champion':'');const badge=document.createElement('div');badge.className='rank';badge.textContent=r.rank;const name=document.createElement('div');name.textContent=r.name+' · '+r.title;const sub=document.createElement('small');sub.textContent='伤害 '+r.damage_dealt+' · 治疗 '+r.healing_done+' · 存活 '+r.survival_time+'s';name.append(sub);const kills=document.createElement('span');kills.textContent=r.kills+' 击败';div.append(badge,name,kills);const detail=document.createElement('details'),summary=document.createElement('summary');summary.textContent='统计与技能';const text=document.createElement('div');text.textContent=`承伤 ${r.damage_received} · 闪避/减伤 ${r.damage_avoided} · 暴击 ${r.critical_hits} · 最大一击 ${r.largest_hit} · 技能 ${r.skills_used} · 鱼干 ${r.food_taken} · HP ${r.hp}\n${r.skills.join(' / ')}`;text.style.whiteSpace='pre-wrap';detail.append(summary,text);detail.append(button('查看技能图鉴',()=>action('skills',{tab:'catalog'}),'skill-link'));div.append(detail);return div;}
function panel(data){current=data;mode=data.mode;if(data.catalog)catalog=data.catalog;document.body.classList.toggle('live-mode',mode==='live');document.body.classList.toggle('book-mode',mode==='skills');for(const id of ['setup','result','live','skills'])$(id).hidden=id!==mode;$('error').textContent=data.error||'';
 if(mode==='setup'){count=data.preferences.count;for(const node of $('counts').children)node.classList.toggle('selected',Number(node.dataset.count)===count);$('setup-summary').textContent=summary(data.preferences);}
 if(mode==='skills'){$('skill-search').value='';$('skill-filter').value='all';draft=structuredClone(data.preferences);readonly=data.readonly;if(readonly&&data.loadouts){draft.fish=data.loadouts;draft.count=data.liveCount;draft.mode='custom';}bookTab=data.tab;renderBook();}
 if(mode==='result'){const result=data.result,w=result.rows.find(r=>r.id===result.winner);$('winner').replaceChildren();const image=document.createElement('img');image.src='../../../../assets/battle/ui/crown.png';$('winner').append(image,document.createTextNode(w?w.name+' 获胜！':'双败 · 本局无冠军'));$('winner-stats').textContent=w?`击败 ${w.kills} · 剩余 HP ${w.hp} · 伤害 ${w.damage_dealt} · 治疗 ${w.healing_done} · 技能 ${w.skills_used} · 存活 ${w.survival_time}s`:'最后的对手同时倒下，双方并列第一。';$('ranking').replaceChildren(...result.rows.map(row));$('records').replaceChildren();const labels={damage_dealt:'伤害最高',healing_done:'治疗最高',kills:'击败最多',damage_received:'承伤最多',largest_hit:'最大一击'};for(const [key,label]of Object.entries(labels)){const r=result.records[key],div=document.createElement('div');div.textContent=label+' · '+r.name+' '+r[key];$('records').append(div);}const h=data.history;$('history').textContent=`本局 ${result.duration}s · 种子 ${result.seed} · 已记录 ${h?.games||1} 局`+(h?.leaders?.length?'\n饭碗榜：'+h.leaders.map(x=>x.title+' '+x.wins+' 冠军').join(' · '):'');$('history').style.whiteSpace='pre-wrap';}
}
const unsub=battleBridge.onPanel(panel),frames=battleBridge.onFrame(data=>{if(mode!=='live')return;paused=data.paused;$('pause').textContent=paused?'继续观战':'暂停观战';$('phase').textContent=paused?'歇一下':data.phase==='countdown'?'马上开打':data.frenzy?'尾巴狂暴中':'正在乱斗';const sec=Math.floor(data.time);$('time').textContent=String(Math.floor(sec/60)).padStart(2,'0')+':'+String(sec%60).padStart(2,'0');$('live-fish').replaceChildren(...data.fish.map(f=>{const div=document.createElement('div');div.className='mini'+(f.alive?'':' dead');div.textContent=f.name+' '+Math.ceil(f.hp);div.title=f.title+' · '+f.skills.map(s=>s.name+(s.ready>0?'（冷却 '+Math.ceil(s.ready)+'s）':'')).join('、');const bar=document.createElement('div');bar.className='mini-bar';bar.style.width=(f.hp/f.maxHp*100)+'%';div.append(bar);return div;}));});
window.addEventListener('error',event=>battleBridge.report(event.message));window.addEventListener('unhandledrejection',event=>battleBridge.report(event.reason?.message||event.reason));
window.__battleDebug={get mode(){return mode;},get count(){return count;},get current(){return current;},get draft(){return draft;},get tab(){return bookTab;}};window.addEventListener('beforeunload',()=>{unsub();frames();});battleBridge.init().then(panel).catch(err=>$('error').textContent=err.message);battleBridge.ready();
