'use strict';
const $=id=>document.getElementById(id), token=decodeURIComponent(location.hash.slice(1).split('&')[0])||sessionStorage.getItem('dshPetToken')||'';
sessionStorage.setItem('dshPetToken',token);
const initialTab=new URLSearchParams(location.hash.slice(1).split('&').slice(1).join('&')).get('tab');
history.replaceState(null,'',location.pathname);
let config={},api={},pets=[],busy=false,toastTimer;
async function request(path,method='GET',body){const r=await fetch(path,{method,headers:{'content-type':'application/json','x-pet-token':token},...(body===undefined?{}:{body:JSON.stringify(body)})});const o=await r.json();if(!r.ok||o.ok===false)throw Error(o.error||o.message||o.reason||'操作失败');return o;}
const portable=(p,m,b)=>request('/portable/api/'+p,m,b), core=(p,m,b)=>request('/dsh-pet-7340/'+p,m,b);
function toast(message,error=false){clearTimeout(toastTimer);$('toast').textContent=message;$('toast').className='visible'+(error?' error':'');toastTimer=setTimeout(()=>$('toast').className='',6500);}
function guard(fn){return async e=>{try{await fn(e);}catch(err){toast(err.message,true);}};}
function element(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e;}
function activePet(){return $('pet-select').value||pets[0]?.id||'main';}
function showTab(name){document.querySelectorAll('.tab').forEach(e=>e.classList.toggle('active',e.id==='tab-'+name));document.querySelectorAll('nav button').forEach(e=>e.classList.toggle('active',e.dataset.tab===name));$('page-title').textContent=document.querySelector(`[data-tab="${name}"]`).textContent;}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
async function refresh(){const o=await portable('settings');api=o.api;config=o.config;pets=config.pets;const old=activePet();$('pet-select').replaceChildren();for(const p of pets){const opt=element('option',p.name||p.id);opt.value=p.id;$('pet-select').append(opt);}if(pets.some(p=>p.id===old))$('pet-select').value=old;
 for(const key of ['protocol','baseUrl','model','providerId','temperature','maxTokens'])$(key).value=api[key];$('apiKey').value='';$('clearKey').checked=false;$('autoStart').checked=api.autoStart;$('key-status').textContent=api.hasApiKey?'密钥已加密保存；留空即可保持原密钥。':'尚未保存密钥；本地模型可留空。';
 for(const key of ['notificationsEnabled','confineToScreen','chatImageEnabled','whisperImageEnabled'])$(key).checked=!!config[key];$('whisperInterval').value=config.eventsRefreshSec?.whisper||300;$('chatMemoryRounds').value=config.chatMemoryRounds??10;$('data-path').textContent='数据目录：'+o.dataPath;$('personality').value=config.whisperPrompt||'';$('chatModel').value=config.chatModel?.model||'';const weights=config.animationWeights;for(const k of ['move','idle','turn'])$('weight-'+k).value=weights[k];$('weight-action').value=Math.round((100-weights.move-weights.idle-weights.turn)*100)/100;$('actionSpeech').checked=config.localSpeech?.actionEnabled!==false;$('allSpeech').checked=pets.every(p=>p.whisperEnabled);$('chatImageLimit').value=config.chatImageLimit??10;for(const key of ['gravity','restitution','groundFriction','throwPower'])$(key).value=config.physics[key];for(const key of ['ceilingBounce'])$(key).checked=!!config.physics[key];$('desktopCollision').checked=config.physics.desktopCollision!==false;
 $('connection').textContent=api.model&&api.baseUrl?'已配置 '+api.model:'API 待配置 · 桌宠已就绪';renderPets();renderAnimations();await loadHistory();}
function labeled(label,control){const l=element('label',label);l.append(control);return l;}
function input(type,value,key){const i=document.createElement('input');i.type=type;if(type==='checkbox')i.checked=!!value;else i.value=value;i.dataset.key=key;return i;}
function renderPets(){const container=$('pet-cards');container.replaceChildren();pets.forEach((p,index)=>{
 const card=element('div',undefined,'pet-card');card.dataset.id=p.id;card.append(element('h3',index===0?'主宠物':'分身 '+index));const name=input('text',p.name||p.id,'name');card.append(labeled('名字',name));const grid=element('div',undefined,'small-grid');const size=input('number',p.size,'size');size.min=80;size.max=1600;grid.append(labeled('大小（px）',size));
 const corner=element('select');corner.dataset.key='corner';for(const [value,label]of [['top-right','右上角'],['top-left','左上角'],['bottom-right','右下角'],['bottom-left','左下角']]){const opt=element('option',label);opt.value=value;corner.append(opt);}corner.value=p.position.corner;grid.append(labeled('起始位置',corner));grid.append(labeled('水平边距',input('number',p.position.marginX,'marginX')),labeled('垂直边距',input('number',p.position.marginY,'marginY')));card.append(grid);
 for(const [key,label]of [['whisperEnabled','点击、动作与碎碎念台词（本地词库）'],['balanceEnabled','显示账户余额'],['workStatusEnabled','跟随工作状态'],['fixedEnabled','原地活动，暂不漫游']]){const l=element('label',undefined,'check');l.append(input('checkbox',p[key],key),document.createTextNode(label));card.append(l);}
 const button=element('button','移除此分身','danger');button.disabled=pets.length<=1;button.onclick=guard(async()=>{await portable('remove','POST',{pet:p.id});toast('已移除分身');await refresh();});card.append(button);container.append(card);
 });}
function currentPets(){return pets.map(p=>{const card=[...document.querySelectorAll('.pet-card')].find(e=>e.dataset.id===p.id);const n={...p,position:{...p.position}};for(const i of card.querySelectorAll('[data-key]')){const k=i.dataset.key;const v=i.type==='checkbox'?i.checked:i.type==='number'?Number(i.value):i.value;if(['corner','marginX','marginY'].includes(k))n.position[k]=v;else n[k]=v;}return n;});}
function renderAnimations(){const names=new Set();function visit(x){if(typeof x==='string')names.add(x);else if(Array.isArray(x))x.forEach(visit);else if(x&&typeof x==='object'){if(typeof x.name==='string')names.add(x.name);else Object.values(x).forEach(visit);}}
 visit(config.animations);$('animation-select').replaceChildren();for(const name of names){const o=element('option',name);o.value=name;$('animation-select').append(o);}}
$('pet-select').onchange=guard(loadHistory);
async function loadHistory(){if(busy)return;const o=await core('chat?pet='+encodeURIComponent(activePet()));const list=o.messages||o.history||[];const box=$('messages');if(!list.length){box.replaceChildren();const empty=element('div',undefined,'empty');const img=element('img');img.src='/portable/logo.png';empty.append(img,element('h3','有什么想跟我说的？'),element('p',api.model?'我是大肥鱼，今天也要陪着你。':'先到「API 与设置」连接模型。'));box.append(empty);return;}box.replaceChildren();list.forEach(m=>box.append(element('div',typeof m.content==='string'?m.content:String(m.text||''),'message '+m.role)));box.scrollTop=box.scrollHeight;}
$('chat-form').onsubmit=guard(async e=>{e.preventDefault();if(busy)return;const text=$('chat-input').value.trim();if(!text)return;if(!api.model||!api.baseUrl){showTab('api');throw Error('请先填写并保存 API 地址与模型');}busy=true;$('send').disabled=true;$('chat-status').textContent='大肥鱼正在想怎么回答…';const empty=$('messages').querySelector('.empty');if(empty)empty.remove();$('messages').append(element('div',text,'message user'));$('chat-input').value='';try{await core('chat?pet='+encodeURIComponent(activePet()),'POST',{text});}finally{busy=false;$('send').disabled=false;$('chat-status').textContent='';await loadHistory();}});
$('chat-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();$('chat-form').requestSubmit();}};
$('clear-memory').onclick=guard(async()=>{await portable('clear-memory','POST',{pet:activePet()});await loadHistory();toast('此分身的记忆已清空');});
$('clone').onclick=guard(async()=>{await portable('clone','POST',{pet:activePet()});toast('分身已加入桌面');await refresh();});
$('save-pets').onclick=guard(async()=>{await portable('config','PUT',{pets:currentPets()});toast('宠物设置已保存');await refresh();});
$('play-animation').onclick=guard(async()=>{await core('anim?pet='+encodeURIComponent(activePet()),'POST',{name:$('animation-select').value});toast('动作已播放');});
$('whisper').onclick=guard(async()=>{await core('whisper?pet='+encodeURIComponent(activePet()),'POST',{});toast('碎碎念已显示在桌宠气泡');});
$('balance').onclick=guard(async()=>{await core('balance','POST',{});const o=await core('state');const b=o.sections?.balance?.data||o.sections?.balance;if(b&&b.ok===false)throw Error(b.message||'这个服务商未提供余额接口');toast('余额已刷新，可查看桌宠气泡');});
$('work-actions').onclick=guard(async e=>{const state=e.target.dataset.state;if(!state)return;await portable('work-status','POST',{state});toast('工作状态已切换');});
$('preset').onchange=()=>{const p=$('preset').value;if(p==='deepseek'){$('protocol').value='openai';$('baseUrl').value='https://api.deepseek.com/v1';$('model').value='deepseek-flash';$('providerId').value='deepseek-official';}else if(p==='anthropic'){$('protocol').value='anthropic';$('baseUrl').value='https://api.anthropic.com/v1';$('model').value='';$('providerId').value='custom';}else if(p==='ollama'){$('protocol').value='openai';$('baseUrl').value='http://127.0.0.1:11434/v1';$('model').value='';$('providerId').value='custom';}};
async function saveApi(){const body={};for(const k of ['protocol','baseUrl','model','providerId'])body[k]=$(k).value.trim();for(const k of ['temperature','maxTokens'])body[k]=Number($(k).value);body.autoStart=$('autoStart').checked;body.apiKey=$('apiKey').value;body.clearKey=$('clearKey').checked;await portable('settings','PUT',body);$('apiKey').value='';await refresh();}
$('api-form').onsubmit=guard(async e=>{e.preventDefault();await saveApi();toast('API 设置已保存');});
$('get-models').onclick=guard(async()=>{await saveApi();const o=await portable('models');$('models').replaceChildren();for(const m of o.models){const opt=element('option');opt.value=m.id;opt.label=m.name;$('models').append(opt);}toast(o.models.length?'已读取 '+o.models.length+' 个模型，可在模型名称中选择':'接口未提供模型列表，请手动填写模型名称');});
$('test-api').onclick=guard(async()=>{$('test-api').disabled=true;try{await saveApi();$('api-status').textContent='正在测试连接…';const o=await portable('test','POST',{});$('api-status').textContent='连接成功：'+o.text;toast('API 连接正常');}finally{$('test-api').disabled=false;}});
$('save-general').onclick=guard(async()=>{const raw=await portable('raw-config');const obj=JSON.parse(raw.text);for(const k of ['notificationsEnabled','confineToScreen','chatImageEnabled','whisperImageEnabled'])obj[k]=$(k).checked;obj.chatMemoryRounds=Number($('chatMemoryRounds').value);obj.whisperPrompt=$('personality').value.trim();obj.chatModel=$('chatModel').value.trim()?{provider:api.providerId,model:$('chatModel').value.trim()}:{provider:'',model:''};delete obj.whisperModel;obj.chatImageLimit=Number($('chatImageLimit').value);obj.physics={...config.physics};for(const k of ['gravity','restitution','groundFriction','throwPower'])obj.physics[k]=Number($(k).value);obj.physics.ceilingBounce=$('ceilingBounce').checked;obj.physics.desktopCollision=$('desktopCollision').checked;obj.physics.petCollision=obj.physics.desktopCollision;if(obj.physics.gravity<0||obj.physics.groundFriction<0||obj.physics.restitution<0||obj.physics.restitution>1||obj.physics.throwPower<=0)throw Error('请检查重力、摩擦、弹性和甩抛力度');obj.eventsRefreshSec={...(config.eventsRefreshSec||{}),whisper:Number($('whisperInterval').value)};if(obj.eventsRefreshSec.whisper<30)throw Error('碎碎念间隔至少为 30 秒');await portable('advanced','PUT',{text:JSON.stringify(obj)});await portable('settings','PUT',{autoStart:$('autoStart').checked});toast('启动和提示设置已保存');await refresh();});
async function loadAdvanced(){const o=await portable('raw-config');$('raw-config').value=o.text;}
$('load-advanced').onclick=guard(loadAdvanced);$('save-advanced').onclick=guard(async()=>{await portable('advanced','PUT',{text:$('raw-config').value});toast('完整配置已保存并重载');await refresh();});
if(initialTab==='pets')showTab('pets');
$('allSpeech').onchange=guard(async()=>{const enabled=$('allSpeech').checked;await portable('config','PUT',{pets:pets.map(p=>({...p,whisperEnabled:enabled}))});toast(enabled?'台词已开启':'台词已关闭');await refresh();});
$('save-weights').onclick=guard(async()=>{const body={};for(const k of ['move','action','idle','turn'])body[k]=Number($('weight-'+k).value);body.actionEnabled=$('actionSpeech').checked;await portable('weights','PUT',body);toast('活动权重已保存，桌宠已重新加载');await refresh();});
$('weight-presets').onclick=e=>{const profiles={quiet:[20,30,45,5],balanced:[35,40,17,8],active:[48,32,12,8],explore:[65,20,7,8]};const v=profiles[e.target.dataset.profile];if(v)['move','action','idle','turn'].forEach((k,i)=>$('weight-'+k).value=v[i]);};
Promise.all([refresh(),loadAdvanced()]).catch(e=>toast(e.message,true));
setInterval(async()=>{if(!busy&&document.querySelector('#tab-chat.active')){try{await loadHistory();}catch{}}},4000);

window.addEventListener("focus",()=>{if(!busy)refresh().catch(e=>toast(e.message,true));});
