'use strict';
const path=require('node:path'),fs=require('node:fs'),{performance}=require('node:perf_hooks');
const {BattleEngine}=require('../core/engine.cjs'),{loadContent}=require('../core/content.cjs');
const {normalizeSetup}=require('../core/setup-config.cjs'),{buildCatalog}=require('../core/catalog.cjs');
class DesktopBattle {
 constructor({electron,normalWindows,geometry,scale,dataDir}){
  this.electron=electron;this.normalWindows=normalWindows;this.geometry=geometry;this.scale=scale;this.dataDir=dataDir;this.content=loadContent();this.engine=null;this.panel=null;this.fishWindows=new Map();this.fxPool=[];this.members=new Map();this.timer=null;this.generation=0;this.starting=false;this.suspended=false;this.paused=false;this.disposed=false;this.finishAt=null;this.resultShown=false;this.latestPanel={mode:'setup'};this.rendererErrors=[];this.metrics={ticks:0,maxTickMs:0,steps:0,droppedSeconds:0,peakFxWindows:0};this.history=this.readHistory();this.catalog=buildCatalog(this.content);this.preferences=this.readPreferences();this.latestPanel=this.setupPanel();this.skillsReturn=null;this.register();
  this.electron.app.on('before-quit',()=>this.dispose());
 }
 register(){const {ipcMain}=this.electron;const allowed=event=>this.members.has(event.sender.id);
  ipcMain.handle('battle:init',event=>{if(!allowed(event))throw Error('未知战斗窗口');return this.latestPanel;});
  ipcMain.handle('battle:action',async(event,payload)=>{if(!allowed(event)||this.members.get(event.sender.id).kind!=='panel')throw Error('仅控制面板可操作战斗');return this.action(payload);});
  ipcMain.on('battle:ready',event=>{const member=this.members.get(event.sender.id);if(member)member.ready=true;});
  ipcMain.on('battle:renderer-error',(event,error)=>{if(!allowed(event))return;this.rendererErrors.push(String(error));if(this.rendererErrors.length>40)this.rendererErrors.shift();this.electron.app.emit('battle-error',String(error));});
 }
 setupPanel(error=''){return {mode:'setup',preferences:{...this.preferences,count:this.setupCount??this.preferences.count},catalog:this.catalog,eventRates:this.content.config.eventRates,maxSkills:this.content.config.setupMaxSkills,maxCans:this.content.config.canCountMax,maxFood:this.content.config.foodCountMax,foodHeal:this.content.config.foodHeal,foodWaveBudget:this.content.config.foodWaveHealBudget,error};}
 readPreferences(){try{return normalizeSetup(JSON.parse(fs.readFileSync(path.join(this.dataDir,'battle-setup.json'),'utf8')),this.content);}catch(error){if(error.code!=='ENOENT')this.rendererErrors.push('已恢复默认配置：'+error.message);return normalizeSetup(null,this.content);}}
 savePreferences(value){const setup=normalizeSetup(value,this.content);fs.mkdirSync(this.dataDir,{recursive:true});const file=path.join(this.dataDir,'battle-setup.json');fs.writeFileSync(file+'.new',JSON.stringify(setup,null,2));fs.renameSync(file+'.new',file);this.preferences=setup;this.setupCount=setup.count;return setup;}
 sendPanel(data,width,height){this.latestPanel=data;if(this.panel&&!this.panel.isDestroyed()){this.place(this.panel,this.panelAt(width,height));this.panel.webContents.send('battle:panel',data);}}
 openSkills(tab='catalog',count=null){if(!['catalog','custom','events'].includes(tab))throw Error('未知配置页');const readonly=!!this.engine;if(!readonly&&count!==null){normalizeSetup({...this.preferences,count,mode:'random'},this.content);this.setupCount=count;}if(this.latestPanel.mode!=='skills')this.skillsReturn=this.latestPanel;this.sendPanel({mode:'skills',tab,readonly,preferences:readonly?this.preferences:this.setupPanel().preferences,loadouts:readonly?this.engine.fish.map(f=>({skills:f.skill_pool.map(s=>s.id),ultimates:f.ultimate_pool.map(s=>s.id)})):null,liveCount:this.engine?.count,catalog:this.catalog,eventRates:this.content.config.eventRates,maxSkills:this.content.config.setupMaxSkills,maxCans:this.content.config.canCountMax,maxFood:this.content.config.foodCountMax,foodHeal:this.content.config.foodHeal,foodWaveBudget:this.content.config.foodWaveHealBudget},550,720);return {ok:true};}
 backSkills(){const back=this.skillsReturn;const data=!back||back.mode==='setup'?this.setupPanel():back;this.skillsReturn=null;this.sendPanel(data,...(data.mode==='live'?[420,305]:data.mode==='result'?[430,650]:[430,610]));return {ok:true};}
 readHistory(){try{const v=JSON.parse(fs.readFileSync(path.join(this.dataDir,'battle-history.json'),'utf8'));return Array.isArray(v)?v.slice(-this.content.config.historyLimit):[];}catch{return[];}}
 saveHistory(result){this.history.push({timestamp:new Date().toISOString(),...result});this.history=this.history.slice(-this.content.config.historyLimit);try{fs.mkdirSync(this.dataDir,{recursive:true});const file=path.join(this.dataDir,'battle-history.json');fs.writeFileSync(file+'.new',JSON.stringify(this.history,null,2));fs.renameSync(file+'.new',file);}catch(error){this.rendererErrors.push('排行榜保存失败：'+error.message);}}
 historySummary(){const leaders=new Map();for(const game of this.history){const w=game.rows.find(r=>r.id===game.winner);if(!w)continue;const v=leaders.get(w.title)||{title:w.title,wins:0};v.wins++;leaders.set(w.title,v);}return {games:this.history.length,leaders:[...leaders.values()].sort((a,b)=>b.wins-a.wins).slice(0,3)};}
 normalPause(pause){this.suspended=pause;for(const win of this.normalWindows.values()){if(win.isDestroyed())continue;win.webContents.send('battle:normal-mode',pause);if(pause){win.setIgnoreMouseEvents(true,{forward:true});win.hide();}else{win.setIgnoreMouseEvents(true,{forward:true});win.showInactive();}}}
 newWindow(kind,width,height){const {BrowserWindow}=this.electron,s=this.scale();const win=new BrowserWindow({width:Math.round(width*s),height:Math.round(height*s),show:false,frame:false,transparent:kind!=='panel',backgroundColor:kind==='panel'?'#f4f9fd':'#00000000',alwaysOnTop:true,skipTaskbar:true,focusable:kind==='panel',resizable:false,hasShadow:kind==='panel',useContentSize:true,webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,backgroundThrottling:false,spellcheck:false}});const contentsId=win.webContents.id,member={win,kind,ready:false,bounds:null};this.members.set(contentsId,member);win.setAlwaysOnTop(true,'screen-saver');if(kind!=='panel')win.setIgnoreMouseEvents(true);win.webContents.setAudioMuted(true);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',event=>event.preventDefault());win.webContents.on('render-process-gone',()=>{if(this.disposed||!this.engine)return;this.stop('战斗窗口异常退出，已恢复桌宠。');});win.on('closed',()=>{this.members.delete(contentsId);if(kind==='fish'&&!this.clearing&&!this.disposed&&this.engine?.fish.some(f=>f.is_alive&&this.fishWindows.get(f.id)===win))this.stop('角色窗口已关闭，已恢复桌宠。');});if(kind==='panel')win.on('close',event=>{if(this.engine&&!this.disposed){event.preventDefault();this.stop();}});win.webContents.on('did-finish-load',()=>win.webContents.setZoomFactor(s));return win;}
 async loadWindow(win,file){await win.loadFile(path.join(__dirname,'../ui',file));if(win.isDestroyed())throw Error('战斗窗口加载时已关闭');}
 place(win,bounds){if(win.isDestroyed())return;const m=this.members.get(win.webContents.id),s=this.scale();const b={x:Math.round(bounds.x*s),y:Math.round(bounds.y*s),width:Math.max(1,Math.round(bounds.width*s)),height:Math.max(1,Math.round(bounds.height*s))};const key=JSON.stringify(b);if(m?.bounds!==key){win.setContentBounds(b,false);if(m)m.bounds=key;}}
 panelAt(width,height){const geo=this.geometry(),a=geo.areas[geo.primaryIndex]||geo.areas[0],s=this.scale();width=Math.min(width,a.width/s-16);height=Math.min(height,a.height/s-16);return {x:(a.x+a.width)/s-width-8,y:a.y/s+Math.min(28,Math.max(8,(a.height/s-height)/2)),width,height};}
 async openSetup(){if(this.disposed)return;if(this.engine){if(this.panel&&!this.panel.isDestroyed()){this.panel.show();this.panel.focus();}return;}if(this.starting)return;
  if(this.panel&&!this.panel.isDestroyed()){this.panel.show();this.panel.focus();return;}this.latestPanel=this.setupPanel();const win=this.panel=this.newWindow('panel',430,610);win.on('close',()=>{if(this.panel===win)this.panel=null;});await this.loadWindow(win,'panel.html');this.place(win,this.panelAt(430,610));win.show();
 }
 async action(payload){switch(payload.action){case 'skills':return this.openSkills(payload.tab,payload.count??null);case 'back-skills':return this.backSkills();case 'save-setup':if(this.engine)throw Error('本局已经开始，请在下局前调整');this.savePreferences(payload.setup);this.skillsReturn=null;this.sendPanel(this.setupPanel(),430,610);return {ok:true};case 'start':return this.start(payload.count,payload.seed);case 'again':return this.start(payload.count);case 'stop':this.stop();return {ok:true};case 'pause':this.paused=!this.paused;return {ok:true};case 'cancel':if(this.panel&&!this.panel.isDestroyed())this.panel.close();return {ok:true};default:throw Error('未知战斗操作');}}
 async start(count,seed=null){if(this.starting)return {ok:false,error:'正在准备乱斗'};if(this.engine&&this.engine.phase!=='finished')return {ok:false,error:'这局还没结束'};if(!Number.isInteger(count)||count<2||count>this.content.config.maxFish)throw Error('请选择 2～10 条大肥鱼');if(seed!==null&&(!Number.isInteger(seed)||seed<0||seed>4294967295))throw Error('随机种子应为 0～4294967295 的整数');
  const setup=normalizeSetup({...this.preferences,count},this.content,count);this.savePreferences(setup);this.skillsReturn=null;this.starting=true;const generation=++this.generation;this.clearBattleWindows();this.resultShown=false;this.finishAt=null;this.paused=false;this.rendererErrors=[];try{
   const s=this.scale(),areas=this.geometry().areas.map(a=>({x:a.x/s,y:a.y/s,width:a.width/s,height:a.height/s}));const engine=this.engine=new BattleEngine({count,seed:seed===null?require('node:crypto').randomInt(0,4294967296):seed,areas,content:this.content,setup,debug:process.env.DSH_PET_BATTLE_DEBUG==='1'});
   const visual=this.content.config.visual;for(const f of engine.fish){if(generation!==this.generation)throw Error('乱斗已取消');const win=this.newWindow('fish',visual.windowWidth,visual.windowHeight);this.fishWindows.set(f.id,win);await this.loadWindow(win,'fish.html');}
   if(generation!==this.generation)throw Error('乱斗已取消');this.normalPause(true);if(!this.panel||this.panel.isDestroyed()){this.panel=this.newWindow('panel',420,270);await this.loadWindow(this.panel,'panel.html');}this.latestPanel={mode:'live',catalog:this.catalog,preferences:this.preferences};this.panel.webContents.send('battle:panel',this.latestPanel);this.place(this.panel,this.panelAt(420,305));this.panel.blur();this.panel.showInactive();this.publish();for(const win of this.fishWindows.values())win.showInactive();this.lastTick=performance.now();this.accumulator=0;this.timer=setInterval(()=>this.tick(),1000/this.content.config.physicsHz);return {ok:true,seed:engine.seed};
  }catch(error){this.stop(error.message);throw error;}finally{this.starting=false;}
 }
 tick(){if(!this.engine||this.disposed)return;const start=performance.now(),dt=Math.min(.5,(start-this.lastTick)/1000);this.lastTick=start;if(this.paused){this.accumulator=0;this.publish();return;}this.accumulator+=dt;const step=1/this.content.config.physicsHz;let steps=0;try{while(this.accumulator>=step&&steps<this.content.config.maxCatchup){this.engine.step(step);this.accumulator-=step;steps++;this.metrics.steps++;}if(this.accumulator>=step){this.metrics.droppedSeconds+=this.accumulator;this.accumulator=0;}this.publish();
   if(this.engine.phase==='finished'){if(this.finishAt===null){this.finishAt=performance.now();this.saveHistory(this.engine.finish);}if(!this.resultShown&&performance.now()-this.finishAt>2600)this.showResult().catch(error=>{if(this.engine)this.stop(error.message);});}
  }catch(error){this.stop('乱斗已安全结束：'+error.message);}this.metrics.ticks++;this.metrics.maxTickMs=Math.max(this.metrics.maxTickMs,performance.now()-start);
 }
 fishFrame(snapshot,f){const area=this.engine.arena.areas.find(a=>f.x>=a.x&&f.x<=a.x+a.width&&f.y>=a.y&&f.y<=a.y+a.height)||this.engine.arena.areas[0];return {fish:f,phase:snapshot.phase,time:snapshot.time,countdown:snapshot.countdown,effects:snapshot.effects.filter(e=>Math.hypot(e.x-f.x,e.y-f.y)<210),nearTop:f.y-area.y<160,nearBottom:area.y+area.height-f.y<150};}
 publish(){if(!this.engine)return;const snap=this.engine.snapshot(),visual=this.content.config.visual;const hud=this.layoutHud(snap);for(const f of snap.fish){const win=this.fishWindows.get(f.id);if(!win||win.isDestroyed())continue;if(!f.alive&&f.deathAge>this.content.config.deathHold){win.destroy();this.fishWindows.delete(f.id);continue;}this.place(win,{x:f.x-visual.centerX,y:f.y-visual.centerY,width:visual.windowWidth,height:visual.windowHeight});win.webContents.send('battle:frame',{...this.fishFrame(snap,f),...hud.get(f.id)});}this.publishEffects(snap);if(this.panel&&!this.panel.isDestroyed()&&this.latestPanel.mode==='live')this.panel.webContents.send('battle:frame',{phase:snap.phase,time:snap.time,frenzy:snap.frenzy,paused:this.paused,fish:snap.fish});}
 layoutHud(snap){
  const occupied=[],layouts=new Map(),overlap=(a,b)=>Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y));
  const fish=snap.fish.filter(f=>f.alive||f.deathAge<=this.content.config.deathHold).sort((a,b)=>a.y-b.y||a.id-b.id);
  for(const f of fish){const area=this.engine.arena.areas.find(a=>f.x>=a.x&&f.x<=a.x+a.width&&f.y>=a.y&&f.y<=a.y+a.height)||this.engine.arena.areas[0];const base=f.y-area.y<160?297:93;let best=null;
   for(const top of [base,65,37,9,297,325])for(const left of [77,17,137]){const rect={x:f.x-175+left,y:f.y-220+top,w:196,h:74};if(rect.x<area.x||rect.x+rect.w>area.x+area.width||rect.y<area.y||rect.y+rect.h>area.y+area.height)continue;const score=occupied.reduce((n,r)=>n+overlap(rect,r),0)*4+Math.abs(top-base)*3+Math.abs(left-77);if(!best||score<best.score)best={top,left,rect,score};}
   if(!best)best={top:base,left:77,rect:{x:f.x-98,y:f.y-220+base,w:196,h:74}};occupied.push(best.rect);layouts.set(f.id,{hudTop:best.top,hudLeft:best.left});
  }
  for(const f of fish){const layout=layouts.get(f.id);if(!f.dialogue)continue;const area=this.engine.arena.areas.find(a=>f.x>=a.x&&f.x<=a.x+a.width&&f.y>=a.y&&f.y<=a.y+a.height)||this.engine.arena.areas[0];const base=f.y-area.y<160?371:30;let best=null;for(const top of [base,4,60,335,371]){const rect={x:Math.max(area.x+4,Math.min(f.x-110,area.x+area.width-224)),y:f.y-220+top,w:220,h:40};if(rect.y<area.y||rect.y+rect.h>area.y+area.height)continue;const score=occupied.reduce((n,r)=>n+overlap(rect,r),0)*4+Math.abs(top-base);if(!best||score<best.score)best={top,rect,score};}if(best){layout.speechTop=best.top;layout.speechLeft=best.rect.x+110-f.x+175;occupied.push(best.rect);}}
  return layouts;
 }
 effectGroups(snap){
  // Effects only: always click-through and non-focusable, never a game container.
  // A display compositor replaces many Chromium renderer processes.
  const objects=[...snap.projectiles,...snap.items,...snap.zones,...snap.effects.filter(e=>e.radius>90||e.type==='banner')];
  for(const h of snap.hazards){objects.push({...h,id:'warning-'+h.id,type:'canWarning'});if(h.progress>.65){const area=this.engine.arena.areas.find(a=>h.x>=a.x&&h.x<=a.x+a.width)||this.engine.arena.areas[0];const p=(h.progress-.65)/.35;objects.push({id:'fall-'+h.id,type:'can',x:h.x,y:area.y-50+(h.y-area.y+50)*p,radius:52,angle:Math.sin(p*4)*.15});}}
  return this.engine.arena.areas.map((area,i)=>({key:'display-'+i,...area,time:snap.time,objects:objects.filter(o=>{const r=Math.max(o.radius||30,30);return o.x+r>=area.x&&o.x-r<=area.x+area.width&&o.y+r>=area.y&&o.y-r-(o.fall||0)<=area.y+area.height;})})).filter(g=>g.objects.length);
 }
 publishEffects(snap){const groups=this.effectGroups(snap);const used=new Set();for(const group of groups){let slot=this.fxPool.find(s=>s.key===group.key&&!used.has(s));if(!slot)slot=this.fxPool.find(s=>!used.has(s)&&!groups.some(g=>g.key===s.key));if(!slot){if(this.fxPool.length>=this.content.config.visual.fxLimit)throw Error('特效窗口数量超过安全上限');const win=this.newWindow('fx',group.width,group.height);slot={win,key:null,loaded:false};this.fxPool.push(slot);const generation=this.generation;this.loadWindow(win,'effects.html').then(()=>{if(generation===this.generation&&!win.isDestroyed())slot.loaded=true;}).catch(error=>{if(generation===this.generation&&this.engine)this.stop(error.message);});}slot.key=group.key;used.add(slot);this.place(slot.win,group);if(slot.loaded&&!slot.win.isDestroyed()){slot.win.webContents.send('battle:frame',group);if(!slot.win.isVisible())slot.win.showInactive();}}
  for(const slot of this.fxPool)if(!used.has(slot)&&!slot.win.isDestroyed()){slot.key=null;slot.win.hide();}this.metrics.peakFxWindows=Math.max(this.metrics.peakFxWindows,this.fxPool.length);
 }
 async showResult(){if(!this.engine?.finish||this.resultShown)return;const generation=this.generation;this.resultShown=true;clearInterval(this.timer);this.timer=null;for(const s of this.fxPool){if(!s.win.isDestroyed())s.win.destroy();}this.fxPool=[];const resultPanel={mode:'result',result:this.engine.finish,history:this.historySummary(),catalog:this.catalog,preferences:this.preferences};if(this.latestPanel.mode==='skills'){this.skillsReturn=resultPanel;return;}this.latestPanel=resultPanel;if(!this.panel||this.panel.isDestroyed()){this.panel=this.newWindow('panel',430,620);await this.loadWindow(this.panel,'panel.html');}if(generation!==this.generation||!this.panel||this.panel.isDestroyed())return;this.place(this.panel,this.panelAt(430,650));this.panel.webContents.send('battle:panel',this.latestPanel);this.panel.showInactive();
 }
 clearBattleWindows(){this.clearing=true;clearInterval(this.timer);this.timer=null;for(const win of this.fishWindows.values())if(!win.isDestroyed())win.destroy();this.fishWindows.clear();for(const slot of this.fxPool)if(!slot.win.isDestroyed())slot.win.destroy();this.fxPool=[];if(this.engine)this.engine.dispose();this.engine=null;this.clearing=false;}
 stop(error=''){++this.generation;this.clearBattleWindows();this.paused=false;this.finishAt=null;this.resultShown=false;if(this.panel&&!this.panel.isDestroyed()){this.panel.destroy();this.panel=null;}if(this.suspended)this.normalPause(false);if(error){console.error('[电子斗蛐蛐] '+error);this.latestPanel=this.setupPanel(error);}else this.latestPanel=this.setupPanel();this.skillsReturn=null;}
 setAreas(){if(!this.engine)return;try{const s=this.scale();this.engine.setAreas(this.geometry().areas.map(a=>({x:a.x/s,y:a.y/s,width:a.width/s,height:a.height/s})));this.publish();}catch(error){this.stop('桌面工作区暂不可用：'+error.message);}}
 dispose(){if(this.disposed)return;this.disposed=true;this.stop();this.electron.ipcMain.removeHandler('battle:init');this.electron.ipcMain.removeHandler('battle:action');}
 audit(){return {engine:this.engine?.phase||null,timer:!!this.timer,fishWindows:this.fishWindows.size,fxWindows:this.fxPool.length,panel:!!this.panel&&!this.panel.isDestroyed(),suspended:this.suspended,starting:this.starting,rendererErrors:[...this.rendererErrors],metrics:{...this.metrics},memberCount:this.members.size};}
}
module.exports={DesktopBattle};
