'use strict';
const {Random,Arena,clamp,distance,direction,segmentDistance}=require('./math.cjs');
const {BattleFish}=require('./fish.cjs');
const {loadContent,loadouts}=require('./content.cjs');
const {normalizeSetup}=require('./setup-config.cjs');
const {createRegistry}=require('../skills/framework.cjs');
const {handlers,advanceActive}=require('../skills/actions.cjs');
const {decide}=require('./ai.cjs');
class BattleEngine {
 constructor({count=2,seed=Date.now(),areas=[{x:0,y:0,width:1920,height:1040}],content=loadContent(),debug=false,setup=null}={}){
  if(!Number.isInteger(count)||count<2||count>content.config.maxFish)throw Error('参战人数必须是 2～10 条');
  this.content=content;this.config=content.config;this.seed=Number(seed)>>>0;this.rng=new Random(this.seed);this.arena=new Arena(areas,this.config.radius+this.config.boundaryPad);this.registry=createRegistry(content.skills,handlers);this.count=count;this.time=0;this.phase='countdown';this.countdown=this.config.countdown;this.objects=[];this.items=[];this.zones=[];this.hazards=[];this.effects=[];this.jobs=[];this.pendingDamage=[];this.objectId=0;this.setup=normalizeSetup(setup,content,count);this.enabledEvents=new Set(this.setup.events);this.eventInterval=this.config.eventRates[this.setup.eventRate].interval;this.nextEvent=this.rng.between(...this.eventInterval);if(!this.enabledEvents.size)this.nextEvent=Infinity;this.lastGlobalSpeech=-100;this.lastGlobalUltimate=-100;this.debug=debug;this.logs=[];this.coverage={casts:{},hits:{},events:{},states:{},damageGraph:{},thirdPartyHits:0,multiThreatHits:0,targetChanges:0};this.frenzy=0;this.finish=null;this.errors=[];this.steps=0;this.maxEntities=0;
  const points=this.arena.spawn(count,this.rng,this.config.radius),pools=loadouts(count,content,this.rng),personas=this.rng.shuffle(content.personalities);
  this.fish=points.map((p,i)=>new BattleFish(i+1,personas[i%personas.length],p,pools[i].map(s=>this.registry.get(s.id)),this.config));
  for(const f of this.fish){const custom=this.setup.fish[f.id-1];if(this.setup.mode==='custom')f.skill_pool=custom.skills.map(id=>this.registry.get(id));f.ultimate_pool=(this.setup.mode==='custom'?custom.ultimates:['29','30']).map(id=>this.registry.get(id));}
 }
 get alive(){return this.fish.filter(f=>f.is_alive);}
 swept(...args){return segmentDistance(...args);}
 log(event,data){if(!this.debug)return;this.logs.push({time:+this.time.toFixed(3),event,...data});console.log('[乱斗 '+this.seed+'] '+this.time.toFixed(2)+' '+event+' '+JSON.stringify(data));if(this.logs.length>this.config.maxLogLines)this.logs.shift();}
 say(f,event,force=false){if(!f)return;const spec=this.content.dialogues[event];if(!spec)return false;const current=f.dialogue&&f.dialogue.until>this.time?f.dialogue.priority:0;const terminal=spec.priority>=10;if(!terminal&&spec.priority<current)return false;if(!force&&!terminal&&(this.time-f.lastSpeech<this.config.dialogueCooldown||this.time-this.lastGlobalSpeech<this.config.globalDialogueGap||this.rng.next()>spec.chance))return false;
  const pool=spec.lines.filter(x=>!f.recentLines.includes(x));const text=this.rng.pick(pool.length?pool:spec.lines);f.recentLines.push(text);if(f.recentLines.length>5)f.recentLines.shift();f.dialogue={text,event,priority:spec.priority,until:this.time+this.config.dialogueDuration};f.lastSpeech=this.time;this.lastGlobalSpeech=this.time;return true;
 }
 effect(type,position,life,owner=null,text='',radius=70,dir=null){if(this.effects.length>=this.config.maxEffects)this.effects.shift();this.effects.push({id:++this.objectId,type,position:{...position},start:this.time,until:this.time+life,owner,text,radius,direction:dir});}
 number(f,value,critical=false){f.numbers.push({id:++this.objectId,text:value>0?'+'+Math.round(value):(critical?'暴击 ':'')+Math.round(value),heal:value>0,critical,start:this.time,until:this.time+this.config.numberLife,offset:this.rng.between(-25,25)});if(f.numbers.length>this.config.maxNumbers)f.numbers.shift();}
 schedule(f,delay,fn){this.jobs.push({owner:f.id,at:this.time+delay,fn});}
 status(f,name,duration,data={}){if(!f.is_alive||this.phase!=='running')return false;
  if(['stun','prison'].includes(name)){if(this.time<f.controlImmuneUntil)return false;f.controlHistory=f.controlHistory.filter(t=>this.time-t<this.config.controlMemory);duration*=Math.max(this.config.controlMinimum,Math.pow(this.config.controlScale,f.controlHistory.length));f.controlHistory.push(this.time);this.cancelCast(f);this.say(f,'stunned');if(data.owner&&data.owner!==f.id)f.hate_table[data.owner]=(f.hate_table[data.owner]||0)+this.config.controlHate;}
  f.status_effects[name]={...data,name,start:this.time,until:this.time+duration};this.effect(name,f.position,.35,f.id);return true;
 }
 cancelCast(f){f.cast=null;f.jumps=null;f.intent={x:0,y:0};f.velocity={x:0,y:0};this.jobs=this.jobs.filter(j=>j.owner!==f.id);}
 damage(attacker,defender,base,spec={}){if(this.phase!=='running'||!defender?.is_alive||!Number.isFinite(base)||base<0)return;this.pendingDamage.push({attacker,defender,base,spec});}
 resolveDamage(){const queue=this.pendingDamage.splice(0);const dying=new Map();
  for(const {attacker:a,defender:d,base,spec:s} of queue){if(!d.is_alive)continue;const dodge=!s.noDodge&&this.rng.next()<this.config.dodgeChance*d.personality.luck;if(dodge){d.damage_avoided+=base;this.say(d,'dodge');this.effect('dodge',d.position,.4,d.id);continue;}
   const critical=!s.noCrit&&a&&this.rng.next()<this.config.critChance*a.personality.luck;const shield=d.status_effects.shield;const modifier=a?.status_effects.rage?.attackMultiplier||1;const damage=Math.max(1,Math.round(base*this.rng.between(...this.config.damageVariance)*(critical?this.config.critMultiplier:1)*modifier*(a?.base_attack||1)*(1+this.frenzy*this.config.frenzyDamageStep)*(1-d.defense)*(1-(shield?.reduction||0))));
   const actual=Math.min(Math.max(0,d.hp),damage);d.hp=Math.max(0,d.hp-damage);d.damage_received+=actual;d.damage_avoided+=shield?damage/(1-shield.reduction)-damage:0;d.last_damage_time=this.time;d.last_attacker=a?.id||null;d.hitTimes=d.hitTimes.filter(t=>this.time-t<this.config.feedback.repeatHitWindow);d.hitTimes.push(this.time);d.hurtUntil=this.time+this.config.hitStun;this.number(d,-damage,critical);
   if(a&&a!==d){a.damage_dealt+=actual;a.largest_hit=Math.max(a.largest_hit,damage);if(critical)a.critical_hits++;d.recentAttackers=(d.recentAttackers||[]).filter(h=>this.time-h.time<this.config.feedback.repeatHitWindow);d.recentAttackers.push({id:a.id,time:this.time});
    const repeats=d.recentAttackers.filter(h=>h.id===a.id).length,hate=damage*this.config.hurtHate+(repeats>=this.config.feedback.repeatHitCount?this.config.repeatHate:0);
    const edge=a.id+'>'+d.id;this.coverage.damageGraph[edge]=(this.coverage.damageGraph[edge]||0)+actual;
    if(d.target&&d.target!==a.id){this.coverage.thirdPartyHits++;this.say(a,'sneak_attack');}
    if(new Set(d.recentAttackers.map(h=>h.id)).size>=2){this.coverage.multiThreatHits++;this.say(d,'surrounded');}d.hate_table[a.id]=Math.min(this.config.hateCap,(d.hate_table[a.id]||0)+hate);this.log('damage',{fish:a.id,target:d.id,damage,hp:d.hp,hate:+d.hate_table[a.id].toFixed(1)});}
   if(a&&a!==d&&(d.hate_table[a.id]||0)>this.config.ai.strongHate)this.say(d,'revenge');if(s.id)this.coverage.hits[s.id]=(this.coverage.hits[s.id]||0)+1;
   if(d.has('prison')){d.status_effects.prison.damage+=damage;if(d.status_effects.prison.damage>=d.status_effects.prison.breakDamage){delete d.status_effects.prison;d.controlImmuneUntil=this.time+this.config.controlImmunity;this.effect('bubbleBurst',d.position,.5,d.id);}}
   const sleeping=d.has('sleep');if(sleeping){delete d.status_effects.sleep;this.cancelCast(d);this.say(d,'sleep_attacked',true);}if(d.has('eating')){const meal=d.status_effects.eating;meal.hits=(meal.hits||[]).filter(h=>this.time-h.time<this.config.healInterruptWindow);meal.hits.push({time:this.time,damage});if(damage>=this.config.healInterrupt||meal.hits.reduce((sum,h)=>sum+h.damage,0)>=this.config.healInterruptTotal){delete d.status_effects.eating;this.cancelCast(d);}}
   if(!sleeping)this.say(d,d.hitTimes.length>=this.config.feedback.repeatHitCount?'multi_hit':critical?'critical_hurt':damage>=this.config.heavyHit?'heavy_hurt':'light_hurt');
   if(s.status==='stun'&&this.rng.next()<(s.chance||1))this.status(d,'stun',s.duration,{owner:a?.id});
   if(s.knockback){const dir=s.direction||(a&&a!==d?direction(a.position,d.position):{x:this.rng.next()<.5?-1:1,y:0});const force=Math.min(this.config.knockbackMax,s.knockback*(critical?1.2:1));d.velocity.x=clamp(d.velocity.x+dir.x*force,-this.config.knockbackMax,this.config.knockbackMax);d.velocity.y=clamp(d.velocity.y+dir.y*force,-this.config.knockbackMax,this.config.knockbackMax);d.knockUntil=this.time+(force>400?.5:.32);d.intent={x:0,y:0};if(force>250&&!d.controlled)this.say(d,'knockback');if(force>250&&d.cast?.phase==='windup')this.cancelCast(d);}
   if(d.has('counter')&&a&&a!==d&&!s.noCounter&&this.rng.next()<d.status_effects.counter.counterChance){d.counterTarget=a.id;d.hate_table[a.id]=(d.hate_table[a.id]||0)+this.config.repeatHate*this.config.feedback.counterRepeatMultiplier;d.nextCast=this.time+this.config.feedback.counterResponseDelay;}
   if(d.hpRatio<this.config.feedback.lowHp&&!d.lowSaid){d.lowSaid=true;this.say(d,'low_hp',true);}
   if(d.hp<=0&&!dying.has(d.id))dying.set(d.id,a&&a!==d?a:null);
   if(a&&a!==d)this.say(a,'attack_success');
  }
  if(dying.size){const before=this.alive.length;for(const [id,killer] of dying){const d=this.fish.find(f=>f.id===id);d.is_alive=false;d.state='DEAD';d.deathAt=this.time;d.deathHold=this.config.deathHold;d.survival_time=this.time;d.rank=before-dying.size+1;d.target=null;this.cancelCast(d);d.status_effects={};d.intent={x:0,y:0};d.deathPosition={...d.position};this.say(d,'death',true);if(killer){killer.kills++;this.say(killer,'kill');}this.log('eliminated',{fish:id,killer:killer?.id});}
   this.objects=this.objects.filter(p=>!dying.has(p.owner));this.zones=this.zones.filter(z=>!dying.has(z.owner));const alive=this.alive;if(alive.length===3||alive.length===2)for(const f of alive)this.say(f,alive.length===2?'final_two':'three_left',true);if(alive.length<=1)this.end(alive[0]||null);
  }
 }
 heal(f,amount,food=false){if(this.phase!=='running'||!f.is_alive)return 0;amount*=Math.max(this.config.frenzyHealFloor,1-this.frenzy*this.config.frenzyHealStep);const thief=this.fish.find(t=>t!==f&&t.is_alive&&t.has('steal')&&distance(t.position,f.position)<f.radius+t.radius+45);if(thief){const stolen=amount*thief.status_effects.steal.stealRatio;amount-=stolen;this.applyHeal(thief,stolen);this.say(thief,'eat');}const healed=this.applyHeal(f,amount);if(food)f.food_taken++;return healed;}
 applyHeal(f,amount){const value=Math.min(f.max_hp-f.hp,Math.max(0,amount));if(value>0){f.hp+=value;f.healing_done+=value;this.number(f,value);this.effect('heal',f.position,.6,f.id);this.say(f,'heal');}return value;}
 projectile(owner,position,velocity,spec,target){if(this.phase!=='running'||!owner.is_alive||this.objects.length>=this.config.maxProjectiles)return null;const dir=direction({x:0,y:0},velocity);const p={id:++this.objectId,owner:owner.id,position:{x:position.x+dir.x*(owner.radius+spec.projectileRadius),y:position.y+dir.y*(owner.radius+spec.projectileRadius)},velocity:{...velocity},damage:spec.damage,lifetime:spec.life,until:this.time+spec.life,hitbox:spec.projectileRadius,effect:spec.effect,target,sprite:spec.effect,destroyed:false,spec,hit:new Set(),bouncesLeft:spec.bounceCount||0};this.objects.push(p);return p;}
 zone(owner,position,spec,follow){if(this.zones.length>=this.config.maxZones)return;this.zones.push({id:++this.objectId,owner:owner.id,position:{...position},spec,follow,until:this.time+spec.active_time,next:this.time});}
 globalEvent(id,owner=null){if(this.phase!=='running')return;id=String(id).padStart(2,'0');if(!this.enabledEvents.has(id))return;this.coverage.events[id]=(this.coverage.events[id]||0)+1;this.log('event',{id});
  const actions={
   '26':()=>{for(let i=0;i<this.setup.foodCount&&this.items.length<this.config.maxItems;i++){const p=this.arena.random(this.rng);this.items.push({id:++this.objectId,type:'food',heal:Math.min(this.config.foodHeal,this.config.foodWaveHealBudget/this.setup.foodCount),position:p,landAt:this.time+.9,landed:false,start:this.time,until:this.time+this.config.foodLife,destroyed:false});}for(const f of this.alive)this.say(f,'food_spawn');},
   '27':()=>{for(const f of this.alive){this.damage(owner,f,this.config.earthquakeDamage,{id:'27',noCounter:true,noDodge:true,noCrit:true});this.status(f,'stun',this.config.earthquakeControl,{owner:owner?.id});this.effect('quake',f.position,.8,f.id);}this.effect('banner',this.alive[0]?.position||this.arena.random(this.rng),1.4,null,'桌面地震 · 尾巴站稳！');},
   '28':()=>{const targets=this.rng.shuffle(this.alive),spots=[];for(let i=0;i<this.setup.canCount;i++){const target=targets[i%targets.length];let p;for(let attempt=0;attempt<12;attempt++){p=target&&this.rng.next()<this.config.canTargetChance?this.arena.clamp({x:target.position.x+this.rng.between(-this.config.canSpread,this.config.canSpread),y:target.position.y+this.rng.between(-this.config.canSpread,this.config.canSpread)},this.config.canRadius):this.arena.random(this.rng,this.config.canRadius);if(spots.every(q=>distance(q,p)>=this.config.canSeparation))break;}spots.push(p);this.hazards.push({id:++this.objectId,type:'can',position:p,radius:this.config.canRadius,start:this.time+i*this.config.canStagger,until:this.time+this.config.canWarning+i*this.config.canStagger,owner:owner?.id});for(const f of this.alive)if(distance(f.position,p)<350)this.say(f,'can_warning',true);}}
  };if(!actions[id])throw Error('未知全局事件：'+id);actions[id]();
 }
 updateObjects(dt){
  for(const p of this.objects){if(p.destroyed)continue;const owner=this.fish.find(f=>f.id===p.owner);if(!owner?.is_alive||this.time>p.until){p.destroyed=true;continue;}const prev={...p.position};if(p.spec.homing||p.bounced){const t=this.fish.find(f=>f.id===p.target&&f.is_alive);if(t){const dir=direction(p.position,t.position);p.velocity={x:dir.x*p.spec.speed,y:dir.y*p.spec.speed};}}
   p.position.x+=p.velocity.x*dt;p.position.y+=p.velocity.y*dt;for(const t of this.fish){if(!t.is_alive||t.id===p.owner||p.hit.has(t.id))continue;if(segmentDistance(t.position,prev,p.position)<t.radius*.78+p.hitbox){this.damage(owner,t,p.damage,p.spec);p.hit.add(t.id);this.effect(p.effect==='hook'?'impact':'bubbleBurst',p.position,.4,p.owner);
    const next=p.bouncesLeft>0?this.alive.filter(x=>x!==owner&&!p.hit.has(x.id)&&distance(x.position,t.position)<p.spec.bounceRadius).sort((a,b)=>distance(a.position,t.position)-distance(b.position,t.position))[0]:null;
    if(next){p.bouncesLeft--;p.target=next.id;p.bounced=true;p.damage*=p.spec.bounceFactor;p.position={...t.position};const dir=direction(p.position,next.position);p.velocity={x:dir.x*p.spec.speed,y:dir.y*p.spec.speed};this.say(owner,'chain_hit');}else p.destroyed=true;break;}}
   if(!this.arena.contains(p.position,0))p.destroyed=true;
  }
  this.objects=this.objects.filter(p=>!p.destroyed);
  for(const z of this.zones){if(z.until<=this.time)continue;const owner=this.fish.find(f=>f.id===z.owner&&f.is_alive);if(!owner){z.until=0;continue;}if(z.follow)z.position={...owner.position};if(this.time>=z.next){z.next=this.time+z.spec.interval;for(const t of this.alive){if(t===owner||distance(t.position,z.position)>z.spec.radius+t.radius*.4)continue;this.damage(owner,t,z.spec.damage,z.spec);if(z.spec.status)this.status(t,z.spec.status,z.spec.duration,{owner:owner.id});}}}
  this.zones=this.zones.filter(z=>z.until>this.time);
  for(const item of this.items){if(item.until<=this.time){item.destroyed=true;continue;}if(!item.landed&&this.time>=item.landAt)item.landed=true;if(!item.landed||item.destroyed)continue;const consumers=this.alive.filter(f=>f.id!==item.owner&&this.time>=(f.nextFoodAt||0)&&distance(f.position,item.position)<f.radius+17).sort((a,b)=>distance(a.position,item.position)-distance(b.position,item.position)||a.id-b.id);if(consumers[0]){item.destroyed=true;consumers[0].nextFoodAt=this.time+this.config.foodPickupGap;this.heal(consumers[0],item.heal||this.config.foodHeal,true);if(item.trap){const owner=this.fish.find(f=>f.id===item.owner&&f.is_alive);if(owner){this.damage(owner,consumers[0],item.trap.damage,item.trap);this.effect('impact',item.position,.6,owner.id);this.say(consumers[0],'bait_caught',true);}}this.status(consumers[0],'snack',.85,{owner:consumers[0].id});this.say(consumers[0],'eat');}}
  this.items=this.items.filter(i=>!i.destroyed&&i.until>this.time);
  for(const h of this.hazards){if(h.until>this.time||h.resolved)continue;h.resolved=true;const owner=this.fish.find(f=>f.id===h.owner);for(const f of this.alive){if(distance(f.position,h.position)<h.radius+f.radius*.6)this.damage(owner,f,this.config.canDamage,{id:'28',knockback:560,direction:direction(h.position,f.position)});}this.effect('canImpact',h.position,.7,null,'',h.radius);}
  this.hazards=this.hazards.filter(h=>!h.resolved);
 }
 updateFish(f,dt){if(!f.is_alive)return;f.survival_time=this.time;f.numbers=f.numbers.filter(n=>n.until>this.time);
  for(const id of Object.keys(f.hate_table)){f.hate_table[id]=Math.max(0,f.hate_table[id]-dt*this.config.hateDecay*f.personality.hateDecay);if(!f.hate_table[id])delete f.hate_table[id];}
  for(const [name,s] of Object.entries(f.status_effects)){if(s.until<=this.time){delete f.status_effects[name];if(['stun','prison'].includes(name))f.controlImmuneUntil=this.time+this.config.controlImmunity;continue;}if(s.heal&&this.time>=s.next){s.next=this.time+s.interval;this.heal(f,s.heal);}}
  if(f.controlled){f.intent={x:0,y:0};f.state='STUNNED';}else if(f.has('sleep'))f.state='SLEEPING';else if(f.has('eating')||f.has('snack'))f.state='HEALING';else if(f.has('shield')||f.has('feign'))f.state='DEFENDING';
  const cast=f.cast;if(cast&&!f.controlled){const elapsed=this.time-cast.start,s=cast.skill;
   if(elapsed>=s.cast_time&&!cast.activated){cast.activated=true;cast.phase='active';try{s.execute(this,f,cast,s);}catch(error){this.errors.push('技能 '+s.id+'：'+error.message);this.log('skillError',{skill:s.id,message:error.message});this.cancelCast(f);}this.say(f,'skill_success');}
   if(f.cast===cast){if(cast.detached){f.cast=null;f.nextCast=Math.min(f.nextCast,this.time+s.recovery_time+this.config.castGap*(f.status_effects.rage?.cooldownMultiplier||1));}else{if(cast.activated&&elapsed<=s.cast_time+s.active_time+1e-5)advanceActive(this,f,cast,dt);if(elapsed>s.cast_time+s.active_time){cast.phase='recovery';if(cast.jump&&!cast.landed){advanceActive(this,f,cast,dt);}}if(elapsed>s.cast_time+s.active_time+s.recovery_time){f.cast=null;f.jumps=null;f.velocity={x:0,y:0};}else if(!f.resting&&!f.has('shield')&&!f.has('feign')&&!['flee','redirect','steal'].includes(s.handler))f.state=cast.phase==='windup'?'CAST_SKILL':'ATTACK';}}
  }
  if(this.time>=f.nextDecision){f.nextDecision=this.time+this.config.decisionInterval+this.rng.between(0,this.config.decisionJitter);decide(this,f);}
  const motion=f.cast?.motion,jump=f.cast?.jump;if(!motion&&!jump){const knocked=this.time<f.knockUntil;
   if(knocked){f.velocity.x*=Math.exp(-dt*this.config.knockbackDrag);f.velocity.y*=Math.exp(-dt*this.config.knockbackDrag);f.state='KNOCKBACK';}else{let ix=f.intent.x,iy=f.intent.y;if(f.controlled||f.resting||f.has('feign'))ix=iy=0;if(f.has('smelly')){ix*=.58;iy*=.58;}if(f.cast&&!['flee','redirect','steal','rage','counter','defend'].includes(f.cast.skill.handler))ix=iy=0;const a=(ix||iy?this.config.acceleration:this.config.deceleration)*dt;f.velocity.x+=clamp(ix-f.velocity.x,-a,a);f.velocity.y+=clamp(iy-f.velocity.y,-a,a);}
   if(f.navigation&&distance(f.position,f.navigation)<this.config.boundaryPad&&!f.controlled&&!f.resting&&!knocked){f.position=this.arena.clamp(f.navigation.portal,f.radius+this.config.boundaryPad);f.navigation=null;f.nextDecision=this.time;this.effect('dash',f.position,.4,f.id);}
   const next={x:f.position.x+f.velocity.x*dt,y:f.position.y+f.velocity.y*dt},bounded=this.arena.clamp(next,f.radius+this.config.boundaryPad);if(Math.abs(next.x-bounded.x)>1)f.velocity.x=0;if(Math.abs(next.y-bounded.y)>1)f.velocity.y=0;f.position=bounded;
  }
  if(f.is_alive&&this.time<f.hurtUntil&&!f.controlled&&!f.resting&&this.time>=f.knockUntil&&!f.cast)f.state='HURT';
  this.coverage.states[f.state]=(this.coverage.states[f.state]||0)+1;
 }
 separate(dt){const alive=this.alive;for(let i=0;i<alive.length;i++)for(let j=i+1;j<alive.length;j++){const a=alive[i],b=alive[j];if(a.cast?.motion||b.cast?.motion||a.cast?.jump||b.cast?.jump)continue;const d=distance(a.position,b.position),min=a.radius+b.radius;if(d>=min)continue;const dir=d<.001?{x:1,y:0}:direction(a.position,b.position);const push=Math.min((min-d)*.25,this.config.separationForce*dt);a.position=this.arena.clamp({x:a.position.x-dir.x*push,y:a.position.y-dir.y*push},a.radius+this.config.boundaryPad);b.position=this.arena.clamp({x:b.position.x+dir.x*push,y:b.position.y+dir.y*push},b.radius+this.config.boundaryPad);}}
 step(dt=1/30){if(this.phase==='disposed')return;if(!Number.isFinite(dt)||dt<=0)return;dt=Math.min(dt,.1);this.steps++;
  if(this.phase==='countdown'){this.countdown=Math.max(0,this.countdown-dt);if(this.countdown<=1e-5){this.phase='running';this.countdown=0;}return;}
  if(this.phase==='finished'){this.time+=dt;return;}
  this.time+=dt;const frenzyStart=this.config.frenzyStart[this.count];const level=this.time<frenzyStart?0:1+Math.floor((this.time-frenzyStart)/this.config.frenzyStep);if(level>this.frenzy){this.frenzy=level;for(const f of this.alive)this.say(f,'frenzy',true);}
  const jobs=this.jobs.filter(j=>j.at<=this.time);this.jobs=this.jobs.filter(j=>j.at>this.time);for(const j of jobs){const owner=this.fish.find(f=>f.id===j.owner);if(owner?.is_alive)try{j.fn();}catch(err){this.errors.push(err.message);}}
  for(const f of this.fish)this.updateFish(f,dt);this.separate(dt);this.updateObjects(dt);
  if(this.time>=this.nextEvent){this.nextEvent=this.time+this.rng.between(...this.eventInterval);const weights=Object.entries(this.config.eventWeights).filter(([id])=>this.enabledEvents.has(id)),total=weights.reduce((sum,[,w])=>sum+w,0),r=this.rng.next()*total;let sum=0;for(const [id,w] of weights){sum+=w;if(r<=sum){this.globalEvent(id);break;}}}
  if(this.time>this.config.maxBattleSeconds&&Math.floor(this.time/this.config.fatigueStep)!==Math.floor((this.time-dt)/this.config.fatigueStep))for(const f of this.alive)this.damage(null,f,this.config.fatigueDamage*(1+this.frenzy),{noDodge:true,noCrit:true,noCounter:true});
  this.resolveDamage();this.effects=this.effects.filter(x=>x.until>this.time);this.maxEntities=Math.max(this.maxEntities,this.objects.length+this.items.length+this.zones.length+this.effects.length);
 }
 end(winner){if(this.phase==='finished'||this.phase==='disposed')return;this.phase='finished';this.pendingDamage=[];this.objects=[];this.items=[];this.zones=[];this.hazards=[];this.jobs=[];this.effects=[];for(const f of this.fish){this.cancelCast(f);f.status_effects={};f.target=null;f.velocity={x:0,y:0};f.intent={x:0,y:0};}
  if(winner){winner.state='VICTORY';winner.rank=1;winner.survival_time=this.time;this.say(winner,'victory',true);}else{for(const f of this.fish.filter(x=>x.deathAt===this.time))f.rank=1;}
  const rows=this.fish.map(f=>({id:f.id,name:f.display_name,title:f.title,personality:f.personality.name,rank:f.rank,hp:Math.round(f.hp),kills:f.kills,damage_dealt:Math.round(f.damage_dealt),damage_received:Math.round(f.damage_received),healing_done:Math.round(f.healing_done),skills_used:f.skills_used,critical_hits:f.critical_hits,damage_avoided:Math.round(f.damage_avoided),survival_time:+f.survival_time.toFixed(1),largest_hit:f.largest_hit,food_taken:f.food_taken,skills:f.skill_pool.map(s=>s.name),skill_ids:f.skill_pool.map(s=>s.id),ultimates:f.ultimate_pool.map(s=>s.name),ultimate_ids:f.ultimate_pool.map(s=>s.id)})).sort((a,b)=>a.rank-b.rank||b.damage_dealt-a.damage_dealt||a.id-b.id);
  this.finish={foodCount:this.setup.foodCount,canCount:this.setup.canCount,setupMode:this.setup.mode,enabledEvents:[...this.enabledEvents],eventRate:this.setup.eventRate,seed:this.seed,duration:+this.time.toFixed(1),count:this.count,winner:winner?.id||null,draw:!winner,rows,records:Object.fromEntries(['damage_dealt','healing_done','kills','damage_received','largest_hit'].map(k=>[k,[...rows].sort((a,b)=>b[k]-a[k])[0]])),errors:[...this.errors]};this.log('finished',{winner:winner?.id||null});
 }
 snapshot(){return {phase:this.phase,time:this.time,countdown:this.countdown,seed:this.seed,frenzy:this.frenzy,fish:this.fish.map(f=>f.snapshot(this.time,this.content.animations)),projectiles:this.objects.map(p=>({id:p.id,type:p.effect,x:p.position.x,y:p.position.y,radius:p.hitbox,angle:Math.atan2(p.velocity.y,p.velocity.x)})),items:this.items.map(i=>({id:i.id,type:'food',x:i.position.x,y:i.position.y,fall:Math.max(0,(i.landAt-this.time)*130)})),hazards:this.hazards.map(h=>({id:h.id,type:'can',x:h.position.x,y:h.position.y,radius:h.radius,progress:clamp((this.time-h.start)/(h.until-h.start),0,1)})),zones:this.zones.map(z=>({id:z.id,type:z.spec.effect,x:z.position.x,y:z.position.y,radius:z.spec.radius})),effects:this.effects.map(f=>({...f,x:f.position.x,y:f.position.y,age:this.time-f.start,progress:clamp((this.time-f.start)/(f.until-f.start),0,1)})),result:this.finish};}
 setAreas(areas){this.arena.set(areas);for(const f of this.fish)f.position=this.arena.clamp(f.position,f.radius+this.config.boundaryPad);for(const i of this.items)i.position=this.arena.clamp(i.position);for(const h of this.hazards)h.position=this.arena.clamp(h.position,h.radius);}
 dispose(){if(this.phase==='disposed')return;this.phase='disposed';for(const f of this.fish){this.cancelCast(f);f.status_effects={};f.numbers=[];f.dialogue=null;}for(const key of ['objects','items','zones','hazards','effects','jobs','pendingDamage','logs'])this[key]=[];}
}
module.exports={BattleEngine};
