'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {BattleEngine}=require('../core/engine.cjs'),{loadContent}=require('../core/content.cjs'),{distance,Arena,Random}=require('../core/math.cjs');
const content=loadContent();
const fresh=(count=3,seed=1)=>{const e=new BattleEngine({count,seed});e.phase='running';for(const f of e.fish){f.nextDecision=1e9;f.position={x:500+f.id*95,y:500};f.personality.luck=0;}return e;};
const advance=(e,seconds)=>{for(let i=0;i<Math.ceil(seconds*30);i++)e.step();};
test('数据完整、无占位、36 个注册执行器和 10 种性格',()=>{assert.equal(content.skills.length,36);assert.equal(content.personalities.length,10);const e=fresh();assert.equal(e.registry.size,36);for(const s of content.skills){assert.equal(typeof e.registry.get(s.id).execute,'function');assert.ok(fs.existsSync(path.join(__dirname,'../../../..','assets/webm',s.animation+'.webm')));}});
test('36 技能逐个实际生效：数值、实体、状态或全局事件',()=>{
 for(const spec of content.skills){const e=fresh();const a=e.fish[0],b=e.fish[1];a.hp=300;b.hp=500;a.position={x:600,y:500};b.position={x:spec.handler==='dash'?780:700,y:500};e.fish[2].position={x:720,y:570};if(spec.handler==='steal')e.status(b,'sleep',8,{heal:35,interval:.5,next:e.time+.5});const skill=e.registry.get(spec.id);const before=b.hp;assert.ok(skill.cast(e,a,b),spec.name+'能发动');advance(e,spec.cast_time+.08);
  if(['defend','feign','counter','flee','redirect','steal','rage'].includes(spec.handler))assert.ok(a.status_effects[spec.status]||a.state==='FLEE',spec.name+'状态生效');
  advance(e,spec.active_time);assert.equal(e.errors.length,0,spec.name);
  if(['melee','aoe','dash','jump','projectile','beam','zone','smoke','prison','ambush','shadows','mutual'].includes(spec.handler))assert.ok(b.hp<before||(e.coverage.hits[spec.id]||0)>0,spec.name+'应命中');
  if(['heal','sleep'].includes(spec.handler))assert.ok(a.healing_done>0,spec.name+'实际回血');
  if(spec.slot==='event')assert.ok(e.coverage.events[spec.id]>0,spec.name+'全局事件生效');
 }
});
test('治疗被明显伤害打断；睡觉偷袭带额外伤害并醒来',()=>{const e=fresh();const[a,b]=e.fish;e.status(b,'eating',10,{heal:50,interval:.5,next:.5});e.damage(a,b,60,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(b.resting,false);e.status(b,'sleep',10,{heal:50,interval:.5,next:.5});e.damage(a,b,100,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(b.has('sleep'),false);assert.equal(b.dialogue.event,'sleep_attacked');});
test('仇恨增加、缓慢衰减，重复命中额外增长',()=>{const e=fresh();const[a,b]=e.fish;e.damage(a,b,30,{noDodge:true,noCrit:true});e.resolveDamage();const first=b.hate_table[a.id];e.damage(a,b,30,{noDodge:true,noCrit:true});e.damage(a,b,30,{noDodge:true,noCrit:true});e.resolveDamage();assert.ok(b.hate_table[a.id]>first*2.6);const hate=b.hate_table[a.id];advance(e,1);assert.ok(b.hate_table[a.id]<hate);});
test('连续控制递减且结束后免疫，不永久眩晕',()=>{const e=fresh();const f=e.fish[0];e.status(f,'stun',2);const duration=f.status_effects.stun.until;advance(e,.2);e.status(f,'stun',2);assert.ok(f.status_effects.stun.until-e.time<duration);advance(e,2);assert.equal(f.controlled,false);});
test('泡泡监狱受到累计伤害破裂，装死可被 AOE 打到',()=>{const e=fresh();const[a,b]=e.fish;e.status(b,'prison',5,{breakDamage:80,damage:0});e.damage(a,b,130,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(b.has('prison'),false);e.status(b,'feign',4);const hp=b.hp;e.damage(a,b,50,{noDodge:true,noCrit:true});e.resolveDamage();assert.ok(b.hp<hp);});
test('反击记住攻击者并提高仇恨，抢食偷取治疗',()=>{const e=fresh();const[a,b]=e.fish;e.status(b,'counter',5,{counterChance:1});e.damage(a,b,30,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(b.counterTarget,a.id);assert.ok(b.hate_table[a.id]>40);a.hp=500;b.hp=500;e.status(a,'steal',5,{stealRatio:.45});e.heal(b,100);assert.equal(a.healing_done,45);assert.equal(b.healing_done,55);});
test('食物同时争抢只有一名领取者',()=>{const e=fresh();for(const f of e.fish){f.position={x:600,y:500};f.hp=500;}e.items=[{id:1,type:'food',position:{x:600,y:500},landed:true,until:5,destroyed:false}];e.updateObjects(1/30);assert.equal(e.items.length,0);assert.equal(e.fish.reduce((n,f)=>n+f.food_taken,0),1);});
test('暴走和反击状态期间仍能出招，冷却实际缩短',()=>{const e=fresh();const[a,b]=e.fish;const rage=e.registry.get('30');rage.cast(e,a,b);advance(e,1.4);assert.ok(a.has('rage'));assert.equal(a.cast,null);a.nextCast=e.time;const bubble=e.registry.get('05');bubble.cast(e,a,b);assert.ok(a.cooldowns['05']-e.time<bubble.cooldown);assert.ok(a.status_effects.rage.until>e.time);e.cancelCast(a);delete a.status_effects.rage;a.nextCast=0;e.registry.get('16').cast(e,a,b);advance(e,.25);assert.ok(a.has('counter'));assert.equal(a.cast,null);});
test('目标死亡、攻击落空、投射物寿命和扫掠命中',()=>{const e=fresh();const[a,b]=e.fish;a.position={x:500,y:500};b.position={x:580,y:500};e.registry.get('02').cast(e,a,b);b.position.x=1100;advance(e,1);assert.equal(b.damage_received,0);e.projectile(a,{x:700,y:700},{x:700,y:0},e.registry.get('08'),b.id);advance(e,2);assert.equal(e.objects.length,0);e.registry.get('06').cast(e,e.fish[2],b);b.is_alive=false;advance(e,2);assert.equal(e.errors.length,0);});
test('边界冲撞和叠加击退不会越界；热更新工作区',()=>{const e=fresh();const[a,b]=e.fish;a.position={x:80,y:500};b.position={x:75,y:500};for(let i=0;i<3;i++)e.damage(a,b,15,{knockback:700,direction:{x:-1,y:0},noDodge:true});e.resolveDamage();advance(e,1);assert.ok(e.arena.contains(b.position,b.radius));e.setAreas([{x:-700,y:-400,width:800,height:600}]);for(const f of e.fish)assert.ok(e.arena.contains(f.position,f.radius));});
test('多屏并集、负坐标、横向与纵向屏缝',()=>{const arena=new Arena([{x:-800,y:0,width:800,height:900},{x:0,y:0,width:1200,height:900}],50);assert.ok(arena.contains({x:0,y:300},50));assert.deepEqual(arena.clamp({x:0,y:300},50),{x:0,y:300});const vertical=new Arena([{x:0,y:-700,width:1200,height:700},{x:0,y:0,width:1200,height:900}],50);assert.ok(vertical.contains({x:500,y:0},50));});
test('断开的显示器工作区可跨越，角色不陷在任务栏接缝',()=>{const e=new BattleEngine({count:2,seed:19,areas:[{x:0,y:0,width:1100,height:700},{x:1300,y:-200,width:900,height:700}]});e.phase='running';e.fish[0].position={x:1030,y:400};e.fish[1].position={x:1470,y:200};advance(e,8);assert.ok(distance(e.fish[0].position,e.fish[1].position)<450);for(const f of e.fish)assert.ok(e.arena.contains(f.position,f.radius));});
test('同归于尽有风险但不保证自杀',()=>{for(const hp of [60,120]){const e=fresh();const[a,b]=e.fish;a.hp=hp;a.position={x:600,y:500};b.position={x:700,y:500};e.registry.get('25').cast(e,a,b);advance(e,1.35);assert.equal(a.is_alive,hp===120);assert.ok(b.damage_received>0);}});
test('同一帧最后两鱼双败，结算后所有攻击失效',()=>{const e=fresh(2);const[a,b]=e.fish;a.hp=b.hp=10;e.damage(a,b,100,{noDodge:true,noCrit:true});e.damage(b,a,100,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(e.phase,'finished');assert.equal(e.finish.draw,true);assert.equal(e.finish.winner,null);assert.ok(e.finish.rows.every(r=>r.rank===1));const hp=a.hp;e.damage(b,a,500);advance(e,3);assert.equal(a.hp,hp);assert.equal(e.jobs.length+e.objects.length+e.hazards.length,0);});
test('淘汰立即停止 AI、延迟发射回调不访问死者',()=>{const e=fresh();const[a,b]=e.fish;e.registry.get('06').cast(e,a,b);e.schedule(a,.3,()=>{throw Error('不能访问死亡角色');});e.damage(b,a,5000,{noDodge:true,noCrit:true});e.resolveDamage();assert.equal(a.state,'DEAD');assert.equal(a.cast,null);advance(e,2);assert.equal(e.errors.length,0);});
test('相同随机种子可重现一局',()=>{const run=()=>{const e=new BattleEngine({count:6,seed:381729});while(!e.finish)e.step();return e.finish;};assert.deepEqual(run(),run());});
test('连锁泡泡实际弹到不同敌人，钩钩产生朝攻击者的拉力',()=>{
 const e=fresh(4);const[a,b,c,d]=e.fish;a.position={x:400,y:500};b.position={x:560,y:500};c.position={x:720,y:500};d.position={x:880,y:500};e.registry.get('31').cast(e,a,b);advance(e,4);assert.ok(e.coverage.hits['31']>=3);assert.ok([b,c,d].every(f=>f.damage_received>0));
 const pull=fresh();const[x,y]=pull.fish;x.position={x:500,y:400};y.position={x:700,y:400};pull.projectile(x,x.position,{x:580,y:0},pull.registry.get('36'),y.id);for(let i=0;i<12&&!pull.pendingDamage.length;i++){pull.time+=1/30;pull.updateObjects(1/30);}pull.resolveDamage();assert.ok(y.velocity.x<0);assert.ok(y.damage_received>0);
});
test('背后偷袭、饭碗诱饵与多人范围技能分别满足自己的条件',()=>{
 const {scores}=require('../core/ai.cjs');const e=fresh(4);const[a,b,c,d]=e.fish;a.position={x:600,y:500};b.position={x:730,y:500};b.facing=1;b.state='CHASE';b.target=c.id;c.position={x:890,y:500};d.position={x:1400,y:700};assert.ok(scores.ambush(e,a,b,e.registry.get('33'))>0);e.registry.get('33').cast(e,a,b);advance(e,.9);assert.ok(b.damage_received>90);
 const trap=fresh(3);const owner=trap.fish[0];owner.position={x:400,y:500};trap.fish[1].position={x:950,y:500};trap.fish[2].position={x:1000,y:650};trap.registry.get('34').cast(trap,owner,trap.fish[1]);advance(trap,.9);assert.equal(trap.items.length,1);for(const f of trap.fish.slice(1)){f.hp=500;f.position={...trap.items[0].position};}trap.updateObjects(1/30);trap.resolveDamage();assert.equal(trap.items.length,0);assert.equal(trap.fish.reduce((n,f)=>n+f.food_taken,0),1);assert.ok(trap.fish.some(f=>f.damage_received>0));
 const crowd=fresh(4);const f=crowd.fish[0];crowd.fish.forEach((x,i)=>x.position=i?{x:600+Math.cos((i-1)*2.1)*130,y:500+Math.sin((i-1)*2.1)*130}:{x:600,y:500});assert.ok(scores.aoe(crowd,f,crowd.fish[1],crowd.registry.get('35'))>0);crowd.registry.get('35').cast(crowd,f,crowd.fish[1]);advance(crowd,.75);assert.ok(crowd.fish.slice(1).every(x=>x.damage_received>0&&x.has('stun')));crowd.fish[3].position.x=1600;assert.equal(scores.aoe(crowd,f,crowd.fish[1],crowd.registry.get('35')),0);
});
test('仇恨能压过第三者机会，十鱼局实际产生混战而不是五组决斗',()=>{
 const {chooseTarget}=require('../core/ai.cjs'),e=fresh(4);const[a,b,c,d]=e.fish;a.target=null;a.hate_table[b.id]=500;c.target=d.id;c.position={x:650,y:500};d.position={x:700,y:500};assert.equal(chooseTarget(e,a).id,b.id);
 for(const seed of [41,99,381729]){const game=new BattleEngine({count:10,seed});while(!game.finish)game.step();const edges=new Set(Object.keys(game.coverage.damageGraph).map(x=>x.split('>').sort((a,b)=>a-b).join('-')));assert.ok(edges.size>=15,`seed ${seed}: ${edges.size} 对真实交手`);assert.ok(game.coverage.thirdPartyHits>15);assert.ok(game.coverage.multiThreatHits>15);assert.ok(game.coverage.targetChanges>20);}
});
test('2～10 人各 30 局、连续多局、状态有限、所有局均结束',()=>{
 const report=[];const start=performance.now();for(let n=2;n<=10;n++){const durations=[];let entities=0,steps=0;for(let i=0;i<30;i++){const e=new BattleEngine({count:n,seed:381729+i*997});while(!e.finish&&e.steps<22000){e.step();for(const f of e.fish)assert.ok(Number.isFinite(f.hp)&&e.arena.contains(f.position,f.radius-1));}assert.ok(e.finish,`${n}人 seed ${e.seed}必须结束`);assert.equal(e.errors.length,0);durations.push(e.time);steps+=e.steps;entities=Math.max(entities,e.maxEntities);e.dispose();e.dispose();assert.equal(e.phase,'disposed');assert.equal(e.objects.length+e.items.length+e.jobs.length+e.pendingDamage.length,0);}report.push({count:n,games:durations.length,min:+Math.min(...durations).toFixed(1),max:+Math.max(...durations).toFixed(1),mean:+(durations.reduce((a,b)=>a+b,0)/durations.length).toFixed(1),maxEntities:entities,steps});}
 const out=process.env.BATTLE_TEST_OUTPUT;if(out){fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'simulation-report.json'),JSON.stringify({games:270,elapsedMs:performance.now()-start,report},null,2));}console.log(JSON.stringify(report));
});

test('图鉴覆盖 36 个技能，描述直接采用配置数值',()=>{const {buildCatalog}=require('../core/catalog.cjs');const c=buildCatalog(content);assert.equal(c.length,36);assert.ok(c.every(s=>s.detail.length>15&&s.condition.length>5&&!s.detail.includes('undefined')));assert.ok(c.find(s=>s.id==='28').detail.includes('默认 3 个'));assert.ok(c.find(s=>s.id==='29').condition.includes('24 秒'));});
test('自选技能逐鱼生效，普通技能和大招严格分槽',()=>{const {defaultSetup,normalizeSetup}=require('../core/setup-config.cjs');const setup=defaultSetup(content);setup.count=10;setup.mode='custom';setup.fish=setup.fish.map((r,i)=>({skills:[String(i+1).padStart(2,'0')],ultimates:i%2?['30']:[]}));const e=new BattleEngine({count:10,seed:44,setup});for(let i=0;i<10;i++){assert.deepEqual(e.fish[i].skill_pool.map(s=>s.id),setup.fish[i].skills);assert.deepEqual(e.fish[i].ultimate_pool.map(s=>s.id),setup.fish[i].ultimates);}e.end(e.fish[0]);assert.deepEqual(e.finish.rows.find(f=>f.id===2).ultimate_ids,['30']);assert.throws(()=>normalizeSetup({...setup,fish:[{skills:['26'],ultimates:[]}]},content));assert.throws(()=>normalizeSetup({...setup,fish:[{skills:['05','05'],ultimates:[]}]},content));assert.throws(()=>normalizeSetup({...setup,fish:[{skills:[],ultimates:[]}]},content));assert.throws(()=>normalizeSetup({...setup,canCount:13},content));assert.throws(()=>normalizeSetup({...setup,canCount:0},content));assert.throws(()=>normalizeSetup({...setup,canCount:3.5},content));});
test('场外全部关闭彻底禁用事件，单项开关与频率生效',()=>{const {defaultSetup}=require('../core/setup-config.cjs');const setup=defaultSetup(content);setup.events=[];const e=new BattleEngine({count:3,seed:52,setup});e.phase='running';e.fish.forEach(f=>f.nextDecision=1e9);for(const id of ['26','27','28'])e.globalEvent(id);advance(e,70);assert.deepEqual(e.coverage.events,{});assert.equal(e.nextEvent,Infinity);assert.equal(e.items.length+e.hazards.length,0);setup.events=['26'];setup.eventRate='lively';const only=new BattleEngine({count:3,seed:53,setup});only.phase='running';only.fish.forEach(f=>f.nextDecision=1e9);assert.ok(only.nextEvent>=10&&only.nextEvent<=18);advance(only,60);assert.ok(only.coverage.events['26']>=3);assert.deepEqual(Object.keys(only.coverage.events),['26']);setup.eventRate='quiet';const quiet=new BattleEngine({setup});assert.ok(quiet.nextEvent>=35&&quiet.nextEvent<=55);});
test('一次 12 个罐头，各有独立预警，命中和战后清理正确',()=>{const {defaultSetup}=require('../core/setup-config.cjs');const setup=defaultSetup(content);setup.canCount=12;const e=new BattleEngine({count:10,seed:73,setup});e.phase='running';e.fish.forEach(f=>f.nextDecision=1e9);e.globalEvent('28');assert.equal(e.hazards.length,12);assert.equal(new Set(e.hazards.map(h=>h.id)).size,12);assert.ok(e.hazards.every(h=>e.arena.contains(h.position,h.radius)));assert.ok(e.hazards.every(h=>h.until-h.start>=1.7-1e-8));advance(e,1.6);assert.equal(e.coverage.hits['28']||0,0);advance(e,3.1);assert.ok(e.coverage.hits['28']>0);assert.equal(e.hazards.length,0);e.globalEvent('28');e.end(e.alive[0]);assert.equal(e.hazards.length,0);assert.equal(e.pendingDamage.length,0);});
test('自选纯恢复等极端组合、关闭场外，连续 2～10 人仍可结算',()=>{const {defaultSetup}=require('../core/setup-config.cjs');for(let n=2;n<=10;n++){const setup=defaultSetup(content);setup.mode='custom';setup.count=n;setup.events=[];setup.fish=setup.fish.map(()=>({skills:['14','17','18'],ultimates:[]}));const e=new BattleEngine({count:n,seed:74+n,setup});while(!e.finish&&e.steps<22000)e.step();assert.ok(e.finish);assert.equal(e.errors.length,0);assert.deepEqual(e.coverage.events,{});assert.equal(e.coverage.casts['29']||0,0);assert.equal(e.coverage.casts['30']||0,0);e.dispose();}});

test('一次 1～12 份小鱼干，逐份唯一领取，库存上限与超时回收',()=>{const {defaultSetup,normalizeSetup}=require('../core/setup-config.cjs');for(const amount of [1,3,12]){const setup=defaultSetup(content);setup.foodCount=amount;setup.events=['26'];const e=new BattleEngine({count:10,seed:95+amount,setup});e.phase='running';e.nextEvent=Infinity;e.fish.forEach(f=>f.nextDecision=1e9);e.globalEvent('26');assert.equal(e.items.length,amount);assert.equal(new Set(e.items.map(i=>i.id)).size,amount);e.time=1;const item=e.items[0],otherItems=e.items.slice(1);e.items=[item];e.fish.slice(2).forEach(f=>f.position={x:100000,y:100000});e.fish[0].position={...item.position};e.fish[1].position={...item.position};e.fish[0].hp=e.fish[1].hp=500;e.updateObjects(1/30);assert.equal(e.fish.reduce((n,f)=>n+f.food_taken,0),1);assert.equal(e.items.length,0);e.items.push(...otherItems);for(let i=0;i<6;i++)e.globalEvent('26');assert.ok(e.items.length<=content.config.maxItems);e.time=30;const beforeHeal=e.fish[0].healing_done;e.fish[0].position={...e.items[0].position};e.updateObjects(1/30);assert.equal(e.items.length,0);assert.equal(e.fish[0].healing_done,beforeHeal);e.dispose();}assert.throws(()=>normalizeSetup({...defaultSetup(content),foodCount:13},content));assert.throws(()=>normalizeSetup({...defaultSetup(content),foodCount:0},content));assert.throws(()=>normalizeSetup({...defaultSetup(content),foodCount:2.5},content));});

test('连续轻伤能打断干饭；小鱼干按整轮预算分摊且吃饭有间隔',()=>{const e=fresh();const[a,b]=e.fish;e.status(b,'eating',4,{heal:22,interval:.5,next:.5});for(let i=0;i<3;i++){e.time=i*.2;e.damage(a,b,22,{noCrit:true,noDodge:true});e.resolveDamage();}assert.equal(b.has('eating'),false);const {defaultSetup}=require('../core/setup-config.cjs');const setup=defaultSetup(content);setup.foodCount=12;const food=new BattleEngine({count:2,seed:124,setup});food.phase='running';food.fish.forEach(f=>f.nextDecision=1e9);food.globalEvent('26');assert.equal(food.items.reduce((sum,item)=>sum+item.heal,0),240);assert.equal(food.items[0].heal,20);food.time=1;const f=food.fish[0];f.hp=500;food.fish[1].position={x:10000,y:10000};for(const item of food.items)item.position={...f.position};food.updateObjects(1/30);assert.equal(f.food_taken,1);assert.equal(f.healing_done,20);food.time=2;food.updateObjects(1/30);assert.equal(f.food_taken,1);food.time=2.3;food.updateObjects(1/30);assert.equal(f.food_taken,2);assert.equal(f.healing_done,40);});
